// Code generated by 'ccgo sys/vfs/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o sys/vfs/vfs_illumos_amd64.go -pkgname vfs', DO NOT EDIT.

package vfs

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	ADMIN_HIGH                           = "ADMIN_HIGH"
	ADMIN_LOW                            = "ADMIN_LOW"
	AD_BOOT                              = 1
	AD_CHECK                             = 2
	AD_CHECK_SUSPEND_TO_DISK             = 2
	AD_CHECK_SUSPEND_TO_RAM              = 21
	AD_COMPRESS                          = 0
	AD_FASTREBOOT                        = 8
	AD_FASTREBOOT_DRYRUN                 = 9
	AD_FORCE                             = 1
	AD_FTRACE_START                      = 1
	AD_FTRACE_STOP                       = 2
	AD_HALT                              = 0
	AD_IBOOT                             = 2
	AD_NOSYNC                            = 7
	AD_POWEROFF                          = 6
	AD_REUSABLE                          = 4
	AD_REUSEFINI                         = 5
	AD_REUSEINIT                         = 3
	AD_SBOOT                             = 3
	AD_SIBOOT                            = 4
	AD_SUSPEND_TO_DISK                   = 0
	AD_SUSPEND_TO_RAM                    = 20
	AD_UNKNOWN                           = -1
	AD_UPDATE_BOOT_CONFIG                = 1
	ALL_ZONES                            = -1
	ATTR_COMM                            = 0x04
	ATTR_EXEC                            = 0x02
	ATTR_HINT                            = 0x08
	ATTR_NOACLCHECK                      = 0x20
	ATTR_REAL                            = 0x10
	ATTR_TRIGGER                         = 0x40
	ATTR_UTIME                           = 0x01
	AT_ALL                               = 49151
	AT_ATIME                             = 0x00100
	AT_BLKSIZE                           = 0x01000
	AT_CTIME                             = 0x00400
	AT_FSID                              = 0x00010
	AT_GID                               = 0x00008
	AT_MODE                              = 0x00002
	AT_MTIME                             = 0x00200
	AT_NBLOCKS                           = 0x02000
	AT_NLINK                             = 0x00040
	AT_NODEID                            = 0x00020
	AT_NOSET                             = 47217
	AT_RDEV                              = 0x00800
	AT_SEQ                               = 0x08000
	AT_SIZE                              = 0x00080
	AT_STAT                              = 4095
	AT_TIMES                             = 1792
	AT_TYPE                              = 0x00001
	AT_UID                               = 0x00004
	AT_XVATTR                            = 0x10000
	AVL_AFTER                            = 1
	AVL_BEFORE                           = 0
	AV_SCANSTAMP_SZ                      = 32
	A_CONFIG                             = 23
	A_DUMP                               = 5
	A_FREEZE                             = 3
	A_FTRACE                             = 15
	A_REBOOT                             = 1
	A_REMOUNT                            = 4
	A_SDTTEST                            = 22
	A_SHUTDOWN                           = 2
	A_SWAPCTL                            = 16
	BOOTARGS_MAX                         = 256
	BOOT_CONFIG_PG_FBBLACKLIST           = "fastreboot_blacklist"
	BOOT_CONFIG_PG_OVR                   = "config_ovr"
	BOOT_CONFIG_PG_PARAMS                = "config"
	CANBSIZ                              = 256
	CC_DONTBLOCK                         = 0x02
	CC_WOULDBLOCK                        = 0x01
	CDLIMIT                              = 2048
	CLOCKS_PER_SEC                       = 1000000
	CLOCK_HIGHRES                        = 4
	CLOCK_LEVEL                          = 10
	CLOCK_MONOTONIC                      = 4
	CLOCK_PROCESS_CPUTIME_ID             = 5
	CLOCK_PROF                           = 2
	CLOCK_REALTIME                       = 3
	CLOCK_THREAD_CPUTIME_ID              = 2
	CLOCK_VIRTUAL                        = 1
	CMASK                                = 022
	CPU_INTR_ACTV_HIGH_LEVEL_MASK        = 0xF800
	CREATE_XATTR_DIR                     = 0x04
	DEFAULT_JUMPPID                      = 0
	DEFAULT_MAXPID                       = 30000
	DEV_BSHIFT                           = 9
	DEV_BSIZE                            = 512
	DISP_LEVEL                           = 11
	DOMINANCE_CHECK                      = 1
	DST_AUST                             = 2
	DST_AUSTALT                          = 10
	DST_CAN                              = 6
	DST_EET                              = 5
	DST_GB                               = 7
	DST_MET                              = 4
	DST_NONE                             = 0
	DST_RUM                              = 8
	DST_TUR                              = 9
	DST_USA                              = 1
	DST_WET                              = 3
	DUMP_ALLOC                           = 0
	DUMP_FREE                            = 1
	DUMP_SCAN                            = 2
	EQUALITY_CHECK                       = 0
	FASTREBOOT_DEFAULT                   = "fastreboot_default"
	FASTREBOOT_ONPANIC                   = "fastreboot_onpanic"
	FASTREBOOT_ONPANIC_CMDLINE           = "fastreboot_onpanic_cmdline"
	FD_SETSIZE                           = 65536
	FMRI_BOOT_CONFIG                     = "svc:/system/boot-config:default"
	FSCALE                               = 256
	FSHIFT                               = 8
	FSTYPSZ                              = 16
	GID_NETADM                           = 65
	GID_NOBODY                           = 60001
	GID_UNKNOWN                          = 96
	GLOBAL_ZONEID                        = 0
	GLOBAL_ZONENAME                      = "global"
	HIGH_LEVELS                          = 5
	IMPLINK_HIGHEXPER                    = 158
	IMPLINK_IP                           = 155
	IMPLINK_LOWEXPER                     = 156
	INADDR_6TO4RRANYCAST                 = 0xc0586301
	INADDR_ALLHOSTS_GROUP                = 0xe0000001
	INADDR_ALLRPTS_GROUP                 = 0xe0000016
	INADDR_ALLRTRS_GROUP                 = 0xe0000002
	INADDR_ANY                           = 0x00000000
	INADDR_BROADCAST                     = 0xffffffff
	INADDR_LOOPBACK                      = 0x7F000001
	INADDR_MAX_LOCAL_GROUP               = 0xe00000ff
	INADDR_NONE                          = 0xffffffff
	INADDR_UNSPEC_GROUP                  = 0xe0000000
	INET6_ADDRSTRLEN                     = 46
	INET_ADDRSTRLEN                      = 16
	IN_AUTOCONF_MASK                     = 0xffff0000
	IN_AUTOCONF_NET                      = 0xa9fe0000
	IN_CLASSA_HOST                       = 0x00ffffff
	IN_CLASSA_MAX                        = 128
	IN_CLASSA_NET                        = 0xff000000
	IN_CLASSA_NSHIFT                     = 24
	IN_CLASSB_HOST                       = 0x0000ffff
	IN_CLASSB_MAX                        = 65536
	IN_CLASSB_NET                        = 0xffff0000
	IN_CLASSB_NSHIFT                     = 16
	IN_CLASSC_HOST                       = 0x000000ff
	IN_CLASSC_NET                        = 0xffffff00
	IN_CLASSC_NSHIFT                     = 8
	IN_CLASSD_HOST                       = 0x0fffffff
	IN_CLASSD_NET                        = 0xf0000000
	IN_CLASSD_NSHIFT                     = 28
	IN_CLASSE_NET                        = 0xffffffff
	IN_LOOPBACKNET                       = 127
	IN_PRIVATE12_MASK                    = 0xfff00000
	IN_PRIVATE12_NET                     = 0xac100000
	IN_PRIVATE16_MASK                    = 0xffff0000
	IN_PRIVATE16_NET                     = 0xc0a80000
	IN_PRIVATE8_MASK                     = 0xff000000
	IN_PRIVATE8_NET                      = 0x0a000000
	IPPORT_BIFFUDP                       = 512
	IPPORT_BOOTPC                        = 68
	IPPORT_BOOTPS                        = 67
	IPPORT_CHARGEN                       = 19
	IPPORT_CMDSERVER                     = 514
	IPPORT_DAYTIME                       = 13
	IPPORT_DHCPV6C                       = 546
	IPPORT_DHCPV6S                       = 547
	IPPORT_DISCARD                       = 9
	IPPORT_DOMAIN                        = 53
	IPPORT_ECHO                          = 7
	IPPORT_EFSSERVER                     = 520
	IPPORT_EXECSERVER                    = 512
	IPPORT_FINGER                        = 79
	IPPORT_FTP                           = 21
	IPPORT_HTTP                          = 80
	IPPORT_HTTP_ALT                      = 8080
	IPPORT_IKE                           = 500
	IPPORT_IKE_NATT                      = 4500
	IPPORT_LDAP                          = 389
	IPPORT_LOGINSERVER                   = 513
	IPPORT_MDNS                          = 5353
	IPPORT_MIP                           = 434
	IPPORT_MTP                           = 57
	IPPORT_NAMESERVER                    = 42
	IPPORT_NETBIOS_DGM                   = 138
	IPPORT_NETBIOS_NS                    = 137
	IPPORT_NETBIOS_SSN                   = 139
	IPPORT_NETSTAT                       = 15
	IPPORT_NTP                           = 123
	IPPORT_PRINTER                       = 515
	IPPORT_RESERVED                      = 1024
	IPPORT_RIPNG                         = 521
	IPPORT_RJE                           = 77
	IPPORT_ROUTESERVER                   = 520
	IPPORT_SLP                           = 427
	IPPORT_SMB                           = 445
	IPPORT_SMTP                          = 25
	IPPORT_SOCKS                         = 1080
	IPPORT_SUPDUP                        = 95
	IPPORT_SYSLOG                        = 514
	IPPORT_SYSTAT                        = 11
	IPPORT_TALK                          = 517
	IPPORT_TELNET                        = 23
	IPPORT_TFTP                          = 69
	IPPORT_TIMESERVER                    = 37
	IPPORT_TTYLINK                       = 87
	IPPORT_USERRESERVED                  = 5000
	IPPORT_VXLAN                         = 4789
	IPPORT_WHOIS                         = 43
	IPPORT_WHOSERVER                     = 513
	IPPROTO_AH                           = 51
	IPPROTO_DSTOPTS                      = 60
	IPPROTO_EGP                          = 8
	IPPROTO_ENCAP                        = 4
	IPPROTO_EON                          = 80
	IPPROTO_ESP                          = 50
	IPPROTO_FRAGMENT                     = 44
	IPPROTO_GGP                          = 3
	IPPROTO_HELLO                        = 63
	IPPROTO_HOPOPTS                      = 0
	IPPROTO_ICMP                         = 1
	IPPROTO_ICMPV6                       = 58
	IPPROTO_IDP                          = 22
	IPPROTO_IGMP                         = 2
	IPPROTO_IP                           = 0
	IPPROTO_IPV6                         = 41
	IPPROTO_MAX                          = 256
	IPPROTO_ND                           = 77
	IPPROTO_NONE                         = 59
	IPPROTO_OSPF                         = 89
	IPPROTO_PIM                          = 103
	IPPROTO_PUP                          = 12
	IPPROTO_RAW                          = 255
	IPPROTO_ROUTING                      = 43
	IPPROTO_RSVP                         = 46
	IPPROTO_SCTP                         = 132
	IPPROTO_TCP                          = 6
	IPPROTO_UDP                          = 17
	IPSEC_PREF_NEVER                     = 0x01
	IPSEC_PREF_REQUIRED                  = 0x02
	IPSEC_PREF_UNIQUE                    = 0x04
	IPV6_ADD_MEMBERSHIP                  = 0x9
	IPV6_BOUND_IF                        = 0x41
	IPV6_CHECKSUM                        = 0x18
	IPV6_DONTFRAG                        = 0x21
	IPV6_DROP_MEMBERSHIP                 = 0xa
	IPV6_DSTOPTS                         = 0xf
	IPV6_FLOWINFO_FLOWLABEL              = 0xffff0f00
	IPV6_FLOWINFO_TCLASS                 = 0x0000f00f
	IPV6_HOPLIMIT                        = 0xc
	IPV6_HOPOPTS                         = 0xe
	IPV6_JOIN_GROUP                      = 0x9
	IPV6_LEAVE_GROUP                     = 0xa
	IPV6_MULTICAST_HOPS                  = 0x7
	IPV6_MULTICAST_IF                    = 0x6
	IPV6_MULTICAST_LOOP                  = 0x8
	IPV6_NEXTHOP                         = 0xd
	IPV6_PAD1_OPT                        = 0
	IPV6_PATHMTU                         = 0x25
	IPV6_PKTINFO                         = 0xb
	IPV6_PREFER_SRC_CGA                  = 0x00000020
	IPV6_PREFER_SRC_CGADEFAULT           = 16
	IPV6_PREFER_SRC_CGAMASK              = 48
	IPV6_PREFER_SRC_COA                  = 0x00000002
	IPV6_PREFER_SRC_DEFAULT              = 21
	IPV6_PREFER_SRC_HOME                 = 0x00000001
	IPV6_PREFER_SRC_MASK                 = 63
	IPV6_PREFER_SRC_MIPDEFAULT           = 1
	IPV6_PREFER_SRC_MIPMASK              = 3
	IPV6_PREFER_SRC_NONCGA               = 0x00000010
	IPV6_PREFER_SRC_PUBLIC               = 0x00000004
	IPV6_PREFER_SRC_TMP                  = 0x00000008
	IPV6_PREFER_SRC_TMPDEFAULT           = 4
	IPV6_PREFER_SRC_TMPMASK              = 12
	IPV6_RECVDSTOPTS                     = 0x28
	IPV6_RECVHOPLIMIT                    = 0x13
	IPV6_RECVHOPOPTS                     = 0x14
	IPV6_RECVPATHMTU                     = 0x24
	IPV6_RECVPKTINFO                     = 0x12
	IPV6_RECVRTHDR                       = 0x16
	IPV6_RECVRTHDRDSTOPTS                = 0x17
	IPV6_RECVTCLASS                      = 0x19
	IPV6_RTHDR                           = 0x10
	IPV6_RTHDRDSTOPTS                    = 0x11
	IPV6_RTHDR_TYPE_0                    = 0
	IPV6_SEC_OPT                         = 0x22
	IPV6_SRC_PREFERENCES                 = 0x23
	IPV6_TCLASS                          = 0x26
	IPV6_UNICAST_HOPS                    = 0x5
	IPV6_UNSPEC_SRC                      = 0x42
	IPV6_USE_MIN_MTU                     = 0x20
	IPV6_V6ONLY                          = 0x27
	IP_ADD_MEMBERSHIP                    = 0x13
	IP_ADD_SOURCE_MEMBERSHIP             = 0x17
	IP_BLOCK_SOURCE                      = 0x15
	IP_BOUND_IF                          = 0x41
	IP_BROADCAST                         = 0x106
	IP_BROADCAST_TTL                     = 0x43
	IP_DEFAULT_MULTICAST_LOOP            = 1
	IP_DEFAULT_MULTICAST_TTL             = 1
	IP_DHCPINIT_IF                       = 0x45
	IP_DONTFRAG                          = 0x1b
	IP_DONTROUTE                         = 0x105
	IP_DROP_MEMBERSHIP                   = 0x14
	IP_DROP_SOURCE_MEMBERSHIP            = 0x18
	IP_HDRINCL                           = 2
	IP_MULTICAST_IF                      = 0x10
	IP_MULTICAST_LOOP                    = 0x12
	IP_MULTICAST_TTL                     = 0x11
	IP_NEXTHOP                           = 0x19
	IP_OPTIONS                           = 1
	IP_PKTINFO                           = 0x1a
	IP_RECVDSTADDR                       = 0x7
	IP_RECVIF                            = 0x9
	IP_RECVOPTS                          = 0x5
	IP_RECVPKTINFO                       = 0x1a
	IP_RECVRETOPTS                       = 0x6
	IP_RECVSLLA                          = 0xa
	IP_RECVTOS                           = 0xc
	IP_RECVTTL                           = 0xb
	IP_RETOPTS                           = 0x8
	IP_REUSEADDR                         = 0x104
	IP_SEC_OPT                           = 0x22
	IP_TOS                               = 3
	IP_TTL                               = 4
	IP_UNBLOCK_SOURCE                    = 0x16
	IP_UNSPEC_SRC                        = 0x42
	ITIMER_PROF                          = 2
	ITIMER_REAL                          = 0
	ITIMER_REALPROF                      = 3
	ITIMER_VIRTUAL                       = 1
	KMC_IDENTIFIER                       = 0x00400000
	KMC_KMEM_ALLOC                       = 0x00200000
	KMC_NODEBUG                          = 0x00020000
	KMC_NOHASH                           = 0x00080000
	KMC_NOMAGAZINE                       = 0x00040000
	KMC_NOTOUCH                          = 0x00010000
	KMC_PREFILL                          = 0x00800000
	KMC_QCACHE                           = 0x00100000
	KM_FLAGS                             = 0xffff
	KM_NORMALPRI                         = 0x0008
	KM_NOSLEEP                           = 0x0001
	KM_NOSLEEP_LAZY                      = 9
	KM_PANIC                             = 0x0002
	KM_PUSHPAGE                          = 0x0004
	KM_SLEEP                             = 0x0000
	KM_VMFLAGS                           = 0x00ff
	KSTAT_DATA_CHAR                      = 0
	KSTAT_DATA_DOUBLE                    = 6
	KSTAT_DATA_FLOAT                     = 5
	KSTAT_DATA_INT32                     = 1
	KSTAT_DATA_INT64                     = 3
	KSTAT_DATA_LONG                      = 3
	KSTAT_DATA_LONGLONG                  = 3
	KSTAT_DATA_STRING                    = 9
	KSTAT_DATA_UINT32                    = 2
	KSTAT_DATA_UINT64                    = 4
	KSTAT_DATA_ULONG                     = 4
	KSTAT_DATA_ULONGLONG                 = 4
	KSTAT_FLAG_DORMANT                   = 0x10
	KSTAT_FLAG_INVALID                   = 0x20
	KSTAT_FLAG_LONGSTRINGS               = 0x40
	KSTAT_FLAG_PERSISTENT                = 0x08
	KSTAT_FLAG_VAR_SIZE                  = 0x02
	KSTAT_FLAG_VIRTUAL                   = 0x01
	KSTAT_FLAG_WRITABLE                  = 0x04
	KSTAT_INTR_HARD                      = 0
	KSTAT_INTR_MULTSVC                   = 4
	KSTAT_INTR_SOFT                      = 1
	KSTAT_INTR_SPURIOUS                  = 3
	KSTAT_INTR_WATCHDOG                  = 2
	KSTAT_IOC_BASE                       = 19200
	KSTAT_IOC_CHAIN_ID                   = 19201
	KSTAT_IOC_READ                       = 19202
	KSTAT_IOC_WRITE                      = 19203
	KSTAT_NUM_INTRS                      = 5
	KSTAT_NUM_TYPES                      = 5
	KSTAT_READ                           = 0
	KSTAT_STRLEN                         = 31
	KSTAT_TYPE_INTR                      = 2
	KSTAT_TYPE_IO                        = 3
	KSTAT_TYPE_NAMED                     = 1
	KSTAT_TYPE_RAW                       = 0
	KSTAT_TYPE_TIMER                     = 4
	KSTAT_WRITE                          = 1
	LINUX_SLL_BROADCAST                  = 1
	LINUX_SLL_HOST                       = 0
	LINUX_SLL_MULTICAST                  = 2
	LINUX_SLL_OTHERHOST                  = 3
	LINUX_SLL_OUTGOING                   = 4
	LOCK_HELD_VALUE                      = 0xff
	LOCK_LEVEL                           = 10
	LOOKUP_DIR                           = 0x01
	LOOKUP_HAVE_SYSATTR_DIR              = 0x08
	LOOKUP_XATTR                         = 0x02
	MAXBSIZE                             = 8192
	MAXFIDSZ                             = 64
	MAXFRAG                              = 8
	MAXLINK                              = 32767
	MAXLINKNAMELEN                       = 32
	MAXNAMELEN                           = 256
	MAXOFFSET_T                          = 0x7fffffffffffffff
	MAXOFF_T                             = 0x7fffffffffffffff
	MAXPATHLEN                           = 1024
	MAXPROJID                            = 2147483647
	MAXSYMLINKS                          = 20
	MAXUID                               = 2147483647
	MAX_CANON                            = 256
	MAX_INPUT                            = 512
	MAX_ZONEID                           = 8191
	MAX_ZONES                            = 8192
	MCAST_BLOCK_SOURCE                   = 0x2b
	MCAST_EXCLUDE                        = 2
	MCAST_INCLUDE                        = 1
	MCAST_JOIN_GROUP                     = 0x29
	MCAST_JOIN_SOURCE_GROUP              = 0x2d
	MCAST_LEAVE_GROUP                    = 0x2a
	MCAST_LEAVE_SOURCE_GROUP             = 0x2e
	MCAST_UNBLOCK_SOURCE                 = 0x2c
	MICROSEC                             = 1000000
	MILLISEC                             = 1000
	MINEPHUID                            = 0x80000000
	MIN_USERZONEID                       = 1
	MIN_ZONEID                           = 0
	MODEMASK                             = 07777
	MO_DEFAULT                           = 1
	MO_EMPTY                             = 0x20
	MO_HASVALUE                          = 0x04
	MO_IGNORE                            = 0x08
	MO_NODISPLAY                         = 0x02
	MO_SET                               = 0x01
	MO_TAG                               = 0x10
	NADDR                                = 13
	NANOSEC                              = 1000000000
	NBBY                                 = 8
	NBPS                                 = 0x20000
	NBPSCTR                              = 512
	NCARGS                               = 2097152
	NCARGS32                             = 0x100000
	NCARGS64                             = 0x200000
	NGROUPS_MAX_DEFAULT                  = 16
	NGROUPS_OLDMAX                       = 32
	NGROUPS_UMAX                         = 1024
	NGROUPS_UMIN                         = 0
	NMOUNT                               = 40
	NOFILE                               = 20
	NZERO                                = 20
	OLD_MAXFIDSZ                         = 16
	PERMMASK                             = 00777
	PIL_MAX                              = 15
	PIPE_BUF                             = 5120
	PIPE_MAX                             = 5120
	PREMOTE                              = 39
	PRIO_CONTRACT                        = 9
	PRIO_GROUP                           = 3
	PRIO_LWP                             = 5
	PRIO_PGRP                            = 1
	PRIO_PROCESS                         = 0
	PRIO_PROJECT                         = 7
	PRIO_SESSION                         = 4
	PRIO_TASK                            = 6
	PRIO_USER                            = 2
	PRIO_ZONE                            = 8
	PROTO_SDP                            = 257
	PTR24_ALIGN                          = 32
	PTR24_BASE                           = 0xe0000000
	PTR24_LSB                            = 5
	PTR24_MSB                            = 29
	P_MYID                               = -1
	REG_LABEL_BP                         = 2
	REG_LABEL_MAX                        = 8
	REG_LABEL_PC                         = 0
	REG_LABEL_R12                        = 4
	REG_LABEL_R13                        = 5
	REG_LABEL_R14                        = 6
	REG_LABEL_R15                        = 7
	REG_LABEL_RBX                        = 3
	REG_LABEL_SP                         = 1
	RLIMIT_AS                            = 6
	RLIMIT_CORE                          = 4
	RLIMIT_CPU                           = 0
	RLIMIT_DATA                          = 2
	RLIMIT_FSIZE                         = 1
	RLIMIT_NOFILE                        = 5
	RLIMIT_STACK                         = 3
	RLIMIT_VMEM                          = 6
	RLIM_NLIMITS                         = 7
	RLIM_NSAVED                          = 7
	RUSAGE_CHILDREN                      = -1
	RUSAGE_LWP                           = 1
	RUSAGE_SELF                          = 0
	RWST_SIG                             = 0x02
	RWST_TRYENTER                        = 0x01
	SCTRSHFT                             = 9
	SEC                                  = 1
	ST_NOSUID                            = 0x02
	ST_NOTRUNC                           = 0x04
	ST_RDONLY                            = 0x01
	SYNC_ALL                             = 0x04
	SYNC_ATTR                            = 0x01
	SYNC_CLOSE                           = 0x02
	SYSNAME                              = 9
	TIMER_ABSTIME                        = 0x1
	TIMER_RELTIME                        = 0x0
	TIME_UTC                             = 0x1
	TYPICALMAXPATHLEN                    = 64
	UA_FASTREBOOT_DEFAULT                = 0x01
	UA_FASTREBOOT_ONPANIC                = 0x02
	UBSIZE                               = 512
	UID_DLADM                            = 15
	UID_NETADM                           = 16
	UID_NOACCESS                         = 60002
	UID_NOBODY                           = 60001
	UID_UNKNOWN                          = 96
	UIOA_ALLOC                           = 0x0001
	UIOA_CLR                             = -16
	UIOA_ENABLED                         = 0x0004
	UIOA_FINI                            = 0x0008
	UIOA_INIT                            = 0x0002
	UIOA_IOV_MAX                         = 16
	UIOA_POLL                            = 0x0010
	UIO_ASYNC                            = 0x0002
	UIO_COPY_CACHED                      = 0x0001
	UIO_COPY_DEFAULT                     = 0x0000
	UIO_XUIO                             = 0x0004
	VDIROPEN                             = 0x800
	VDUP                                 = 0x08
	VEXEC                                = 00100
	VFSFT_ACCESS_FILTER                  = 0x100000080
	VFSFT_ACEMASKONACCESS                = 0x100000020
	VFSFT_ACLONCREATE                    = 0x100000010
	VFSFT_CASEINSENSITIVE                = 0x100000002
	VFSFT_DIRENTFLAGS                    = 0x100000008
	VFSFT_NOCASESENSITIVE                = 0x100000004
	VFSFT_REPARSE                        = 0x100000100
	VFSFT_SYSATTR_VIEWS                  = 0x100000040
	VFSFT_XVATTR                         = 0x100000001
	VFSFT_ZEROCOPY_SUPPORTED             = 0x100000200
	VFSNAME_FREEVFS                      = "freevfs"
	VFSNAME_MOUNT                        = "mount"
	VFSNAME_MOUNTROOT                    = "mountroot"
	VFSNAME_ROOT                         = "root"
	VFSNAME_STATVFS                      = "statvfs"
	VFSNAME_SYNC                         = "sync"
	VFSNAME_UNMOUNT                      = "unmount"
	VFSNAME_VGET                         = "vget"
	VFSNAME_VNSTATE                      = "vnstate"
	VFSSP_VERBATIM                       = 0x1
	VFS_CREATEOPT                        = 0x08
	VFS_DISPLAY                          = 0x02
	VFS_NBMAND                           = 0x200
	VFS_NODEVICES                        = 0x800
	VFS_NODISPLAY                        = 0x04
	VFS_NOEXEC                           = 0x1000
	VFS_NOFORCEOPT                       = 0x01
	VFS_NOMNTPT                          = "unspecified_mountpoint"
	VFS_NOMNTTAB                         = 0x02
	VFS_NORESOURCE                       = "unspecified_resource"
	VFS_NOSETUID                         = 0x08
	VFS_NOTRUNC                          = 0x20
	VFS_PXFS                             = 0x80
	VFS_RDONLY                           = 0x01
	VFS_REMOUNT                          = 0x10
	VFS_STATS                            = 0x2000
	VFS_UNLINKABLE                       = 0x40
	VFS_UNMOUNTED                        = 0x100
	VFS_XATTR                            = 0x400
	VFS_XID                              = 0x4000
	VISSWAP                              = 0x40
	VISSWAPFS                            = 0x20000
	VMC_DUMPSAFE                         = 0x00200000
	VMC_FLAGS                            = 0xFFFF0000
	VMC_IDENTIFIER                       = 0x00040000
	VMC_NO_QCACHE                        = 0x00020000
	VMC_POPULATOR                        = 0x00010000
	VMC_XALIGN                           = 0x00100000
	VMC_XALLOC                           = 0x00080000
	VMEM_ALLOC                           = 0x01
	VMEM_FREE                            = 0x02
	VMEM_REENTRANT                       = 0x80000000
	VMEM_ROTOR                           = 0x20
	VMEM_SPAN                            = 0x10
	VMEM_WALKER                          = 0x40
	VMODSORT                             = 65536
	VM_ABORT                             = 0x00002000
	VM_BESTFIT                           = 0x00000100
	VM_ENDALLOC                          = 0x00004000
	VM_FIRSTFIT                          = 0x00000200
	VM_FLAGS                             = 0x0000FFFF
	VM_KMFLAGS                           = 0x000000ff
	VM_MEMLOAD                           = 0x00000800
	VM_NEXTFIT                           = 0x00000400
	VM_NORELOC                           = 0x00001000
	VM_NORMALPRI                         = 0x00000008
	VM_NOSLEEP                           = 0x00000001
	VM_PANIC                             = 0x00000002
	VM_PUSHPAGE                          = 0x00000004
	VM_SLEEP                             = 0x00000000
	VNOCACHE                             = 0x02
	VNODE_ALIGN                          = 64
	VNODE_ALIGN_LOG2                     = 8
	VNOMAP                               = 0x04
	VNOMOUNT                             = 0x20
	VNOSWAP                              = 0x10
	VOPNAME_ACCESS                       = "access"
	VOPNAME_ADDMAP                       = "addmap"
	VOPNAME_CLOSE                        = "close"
	VOPNAME_CMP                          = "cmp"
	VOPNAME_CREATE                       = "create"
	VOPNAME_DELMAP                       = "delmap"
	VOPNAME_DISPOSE                      = "dispose"
	VOPNAME_DUMP                         = "dump"
	VOPNAME_DUMPCTL                      = "dumpctl"
	VOPNAME_FID                          = "fid"
	VOPNAME_FRLOCK                       = "frlock"
	VOPNAME_FSYNC                        = "fsync"
	VOPNAME_GETATTR                      = "getattr"
	VOPNAME_GETPAGE                      = "getpage"
	VOPNAME_GETSECATTR                   = "getsecattr"
	VOPNAME_INACTIVE                     = "inactive"
	VOPNAME_IOCTL                        = "ioctl"
	VOPNAME_LINK                         = "link"
	VOPNAME_LOOKUP                       = "lookup"
	VOPNAME_MAP                          = "map"
	VOPNAME_MKDIR                        = "mkdir"
	VOPNAME_OPEN                         = "open"
	VOPNAME_PAGEIO                       = "pageio"
	VOPNAME_PATHCONF                     = "pathconf"
	VOPNAME_POLL                         = "poll"
	VOPNAME_PUTPAGE                      = "putpage"
	VOPNAME_READ                         = "read"
	VOPNAME_READDIR                      = "readdir"
	VOPNAME_READLINK                     = "readlink"
	VOPNAME_REALVP                       = "realvp"
	VOPNAME_REMOVE                       = "remove"
	VOPNAME_RENAME                       = "rename"
	VOPNAME_REQZCBUF                     = "reqzcbuf"
	VOPNAME_RETZCBUF                     = "retzcbuf"
	VOPNAME_RMDIR                        = "rmdir"
	VOPNAME_RWLOCK                       = "rwlock"
	VOPNAME_RWUNLOCK                     = "rwunlock"
	VOPNAME_SEEK                         = "seek"
	VOPNAME_SETATTR                      = "setattr"
	VOPNAME_SETFL                        = "setfl"
	VOPNAME_SETSECATTR                   = "setsecattr"
	VOPNAME_SHRLOCK                      = "shrlock"
	VOPNAME_SPACE                        = "space"
	VOPNAME_SYMLINK                      = "symlink"
	VOPNAME_VNEVENT                      = "vnevent"
	VOPNAME_WRITE                        = "write"
	VOPSTATS_STR                         = "vopstats_"
	VPXFS                                = 0x2000
	VREAD                                = 00400
	VROOT                                = 0x01
	VSA_ACE                              = 0x0010
	VSA_ACECNT                           = 0x0020
	VSA_ACE_ACLFLAGS                     = 0x0080
	VSA_ACE_ALLTYPES                     = 0x0040
	VSA_ACL                              = 0x0001
	VSA_ACLCNT                           = 0x0002
	VSA_DFACL                            = 0x0004
	VSA_DFACLCNT                         = 0x0008
	VSGID                                = 02000
	VSUID                                = 04000
	VSVTX                                = 01000
	VSWAPLIKE                            = 0x80
	VSW_CANLOFI                          = 0x80
	VSW_CANREMOUNT                       = 0x04
	VSW_CANRWRO                          = 0x02
	VSW_HASPROTO                         = 0x01
	VSW_INSTALLED                        = 0x8000
	VSW_MOUNTDEV                         = 0x200
	VSW_NOTZONESAFE                      = 0x08
	VSW_STATS                            = 0x20
	VSW_VOLATILEDEV                      = 0x10
	VSW_XID                              = 0x40
	VSW_ZMOUNT                           = 0x100
	VTRAVERSE                            = 0x80000
	VVFSLOCK                             = 0x100
	VVFSWAIT                             = 0x200
	VVMEXEC                              = 0x1000
	VVMLOCK                              = 0x400
	VWRITE                               = 00200
	V_ACE_MASK                           = 0x1
	V_APPEND                             = 0x2
	V_FALSE                              = 0
	V_LOCALITY                           = 0x8000
	V_RDDIR_ACCFILTER                    = 0x02
	V_RDDIR_ENTFLAGS                     = 0x01
	V_SYSATTR                            = 0x40000
	V_TRUE                               = 1
	V_WRITELOCK_FALSE                    = 0
	V_WRITELOCK_TRUE                     = 1
	V_XATTRDIR                           = 0x4000
	XAT0_APPENDONLY                      = 0x00000080
	XAT0_ARCHIVE                         = 0x00000002
	XAT0_AV_MODIFIED                     = 0x00000800
	XAT0_AV_QUARANTINED                  = 0x00000400
	XAT0_AV_SCANSTAMP                    = 0x00001000
	XAT0_CREATETIME                      = 0x00000001
	XAT0_GEN                             = 0x00004000
	XAT0_HIDDEN                          = 0x00000010
	XAT0_IMMUTABLE                       = 0x00000040
	XAT0_INDEX                           = 0
	XAT0_NODUMP                          = 0x00000100
	XAT0_NOUNLINK                        = 0x00000020
	XAT0_OFFLINE                         = 0x00008000
	XAT0_OPAQUE                          = 0x00000200
	XAT0_PROJID                          = 0x00040000
	XAT0_PROJINHERIT                     = 0x00020000
	XAT0_READONLY                        = 0x00000008
	XAT0_REPARSE                         = 0x00002000
	XAT0_SPARSE                          = 0x00010000
	XAT0_SYSTEM                          = 0x00000004
	XAT_APPENDONLY                       = 128
	XAT_ARCHIVE                          = 2
	XAT_AV_MODIFIED                      = 2048
	XAT_AV_QUARANTINED                   = 1024
	XAT_AV_SCANSTAMP                     = 4096
	XAT_CREATETIME                       = 1
	XAT_GEN                              = 16384
	XAT_HIDDEN                           = 16
	XAT_IMMUTABLE                        = 64
	XAT_NODUMP                           = 256
	XAT_NOUNLINK                         = 32
	XAT_OFFLINE                          = 32768
	XAT_OPAQUE                           = 512
	XAT_PROJID                           = 262144
	XAT_PROJINHERIT                      = 131072
	XAT_READONLY                         = 8
	XAT_REPARSE                          = 8192
	XAT_SPARSE                           = 65536
	XAT_SYSTEM                           = 4
	XVA_MAGIC                            = 0x78766174
	XVA_MAPSIZE                          = 3
	XVA_MASK                             = 0xffffffff
	XVA_SHFT                             = 32
	ZCF_NET_EXCL                         = 0x1
	ZE_AREMOUNTS                         = 2
	ZE_CHROOTED                          = 1
	ZE_LABELINUSE                        = 3
	ZE_UNKNOWN                           = 0
	ZF_HASHED_LABEL                      = 0x2
	ZF_IS_SCRATCH                        = 0x4
	ZF_NET_EXCL                          = 0x8
	ZF_REFCOUNTS_LOGGED                  = 0x1
	ZONEID_WIDTH                         = 4
	ZONENAME_MAX                         = 64
	ZONENAME_REGEXP                      = "[a-zA-Z0-9][-_.a-zA-Z0-9]{0,62}"
	ZONES_TMPDIR                         = "/var/run/zones"
	ZONE_ADD_DATALINK                    = 10
	ZONE_ATTR_APP_SVC_CT                 = 31
	ZONE_ATTR_BOOTARGS                   = 10
	ZONE_ATTR_BRAND                      = 11
	ZONE_ATTR_BRAND_ATTRS                = 32768
	ZONE_ATTR_DID                        = 30
	ZONE_ATTR_FLAGS                      = 14
	ZONE_ATTR_FS_ALLOWED                 = 16
	ZONE_ATTR_HOSTID                     = 15
	ZONE_ATTR_INITNAME                   = 9
	ZONE_ATTR_INITNORESTART              = 20
	ZONE_ATTR_INITPID                    = 7
	ZONE_ATTR_INITREBOOT                 = 23
	ZONE_ATTR_INITRESTART0               = 22
	ZONE_ATTR_NAME                       = 2
	ZONE_ATTR_NETWORK                    = 17
	ZONE_ATTR_POOLID                     = 6
	ZONE_ATTR_PRIVSET                    = 4
	ZONE_ATTR_ROOT                       = 1
	ZONE_ATTR_SCHED_CLASS                = 13
	ZONE_ATTR_SCHED_FIXEDHI              = 32
	ZONE_ATTR_SECFLAGS                   = 21
	ZONE_ATTR_SLBL                       = 8
	ZONE_ATTR_STATUS                     = 3
	ZONE_ATTR_UNIQID                     = 5
	ZONE_BOOT                            = 7
	ZONE_CB_NAME                         = "zonename"
	ZONE_CB_NEWSTATE                     = "newstate"
	ZONE_CB_OLDSTATE                     = "oldstate"
	ZONE_CB_TIMESTAMP                    = "when"
	ZONE_CB_ZONEID                       = "zoneid"
	ZONE_CHECK_DATALINK                  = 12
	ZONE_CREATE                          = 0
	ZONE_DEL_DATALINK                    = 11
	ZONE_DESTROY                         = 1
	ZONE_ENTER                           = 3
	ZONE_EVENT_CHANNEL                   = "com.sun:zones:status"
	ZONE_EVENT_INITIALIZED               = "initialized"
	ZONE_EVENT_READY                     = "ready"
	ZONE_EVENT_RUNNING                   = "running"
	ZONE_EVENT_SHUTTING_DOWN             = "shutting_down"
	ZONE_EVENT_STATUS_CLASS              = "status"
	ZONE_EVENT_STATUS_SUBCLASS           = "change"
	ZONE_EVENT_UNINITIALIZED             = "uninitialized"
	ZONE_FS_ALLOWED_MAX                  = 1024
	ZONE_GETATTR                         = 2
	ZONE_LIST                            = 4
	ZONE_LIST_DATALINK                   = 13
	ZONE_LOOKUP                          = 6
	ZONE_NETWORK_ADDRESS                 = 1
	ZONE_NETWORK_DEFROUTER               = 2
	ZONE_NET_ADDRNAME                    = "address"
	ZONE_NET_RTRNAME                     = "route"
	ZONE_SETATTR                         = 9
	ZONE_SHUTDOWN                        = 5
	ZONE_SUBPROC_FATAL                   = 255
	ZONE_SUBPROC_NOTCOMPLETE             = 254
	ZONE_SUBPROC_OK                      = 0
	ZONE_SUBPROC_USAGE                   = 253
	ZONE_VERSION                         = 8
	X_ACL_ACE_ENABLED                    = 0x2
	X_ACL_ACLENT_ENABLED                 = 0x1
	X_ALIGNMENT_REQUIRED                 = 1
	X_AVL_H                              = 0
	X_AVL_IMPL_H                         = 0
	X_BIT_FIELDS_LTOH                    = 0
	X_BOOL_ALIGNMENT                     = 1
	X_CASE_INSENSITIVE                   = 0x2
	X_CASE_SENSITIVE                     = 0x1
	X_CHAR_ALIGNMENT                     = 1
	X_CHAR_IS_SIGNED                     = 0
	X_CLOCKID_T                          = 0
	X_CLOCK_T                            = 0
	X_COND_MAGIC                         = 0x4356
	X_CS_LFS64_CFLAGS                    = 72
	X_CS_LFS64_LDFLAGS                   = 73
	X_CS_LFS64_LIBS                      = 74
	X_CS_LFS64_LINTFLAGS                 = 75
	X_CS_LFS_CFLAGS                      = 68
	X_CS_LFS_LDFLAGS                     = 69
	X_CS_LFS_LIBS                        = 70
	X_CS_LFS_LINTFLAGS                   = 71
	X_CS_PATH                            = 65
	X_CS_POSIX_V6_ILP32_OFF32_CFLAGS     = 800
	X_CS_POSIX_V6_ILP32_OFF32_LDFLAGS    = 801
	X_CS_POSIX_V6_ILP32_OFF32_LIBS       = 802
	X_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS  = 803
	X_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS    = 804
	X_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS   = 805
	X_CS_POSIX_V6_ILP32_OFFBIG_LIBS      = 806
	X_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS = 807
	X_CS_POSIX_V6_LP64_OFF64_CFLAGS      = 808
	X_CS_POSIX_V6_LP64_OFF64_LDFLAGS     = 809
	X_CS_POSIX_V6_LP64_OFF64_LIBS        = 810
	X_CS_POSIX_V6_LP64_OFF64_LINTFLAGS   = 811
	X_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS    = 812
	X_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS   = 813
	X_CS_POSIX_V6_LPBIG_OFFBIG_LIBS      = 814
	X_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS = 815
	X_CS_POSIX_V6_WIDTH_RESTRICTED_ENVS  = 816
	X_CS_XBS5_ILP32_OFF32_CFLAGS         = 700
	X_CS_XBS5_ILP32_OFF32_LDFLAGS        = 701
	X_CS_XBS5_ILP32_OFF32_LIBS           = 702
	X_CS_XBS5_ILP32_OFF32_LINTFLAGS      = 703
	X_CS_XBS5_ILP32_OFFBIG_CFLAGS        = 705
	X_CS_XBS5_ILP32_OFFBIG_LDFLAGS       = 706
	X_CS_XBS5_ILP32_OFFBIG_LIBS          = 707
	X_CS_XBS5_ILP32_OFFBIG_LINTFLAGS     = 708
	X_CS_XBS5_LP64_OFF64_CFLAGS          = 709
	X_CS_XBS5_LP64_OFF64_LDFLAGS         = 710
	X_CS_XBS5_LP64_OFF64_LIBS            = 711
	X_CS_XBS5_LP64_OFF64_LINTFLAGS       = 712
	X_CS_XBS5_LPBIG_OFFBIG_CFLAGS        = 713
	X_CS_XBS5_LPBIG_OFFBIG_LDFLAGS       = 714
	X_CS_XBS5_LPBIG_OFFBIG_LIBS          = 715
	X_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS     = 716
	X_DMA_USES_PHYSADDR                  = 0
	X_DONT_USE_1275_GENERIC_NAMES        = 0
	X_DOUBLE_ALIGNMENT                   = 8
	X_DOUBLE_COMPLEX_ALIGNMENT           = 8
	X_DTRACE_VERSION                     = 1
	X_FILE_OFFSET_BITS                   = 64
	X_FIRMWARE_NEEDS_FDISK               = 0
	X_FLOAT_ALIGNMENT                    = 4
	X_FLOAT_COMPLEX_ALIGNMENT            = 4
	X_FSTYPSZ                            = 16
	X_HAVE_CPUID_INSN                    = 0
	X_IEEE_754                           = 0
	X_INT64_TYPE                         = 0
	X_INT_ALIGNMENT                      = 4
	X_IN_ADDR_T                          = 0
	X_IN_PORT_T                          = 0
	X_IPADDR_T                           = 0
	X_ISO_CPP_14882_1998                 = 0
	X_ISO_C_9899_1999                    = 0
	X_ISO_C_9899_2011                    = 0
	X_ISO_TIME_ISO_H                     = 0
	X_LARGEFILE64_SOURCE                 = 1
	X_LARGEFILE_SOURCE                   = 1
	X_LITTLE_ENDIAN                      = 0
	X_LOCALE_T                           = 0
	X_LONGLONG_TYPE                      = 0
	X_LONG_ALIGNMENT                     = 8
	X_LONG_DOUBLE_ALIGNMENT              = 16
	X_LONG_DOUBLE_COMPLEX_ALIGNMENT      = 16
	X_LONG_LONG_ALIGNMENT                = 8
	X_LONG_LONG_ALIGNMENT_32             = 4
	X_LONG_LONG_LTOH                     = 0
	X_LP64                               = 1
	X_MAX_ALIGNMENT                      = 16
	X_MULTI_DATAMODEL                    = 0
	X_MUTEX_MAGIC                        = 0x4d58
	X_NBBY                               = 8
	X_NETINET_IN_H                       = 0
	X_NET_IF_DL_H                        = 0
	X_NORETURN_KYWD                      = 0
	X_OFF_T                              = 0
	X_OLD_IPV6_RECVDSTOPTS               = 0x15
	X_PC_2_SYMLINKS                      = 19
	X_PC_ACCESS_FILTERING                = 25
	X_PC_ACL_ENABLED                     = 20
	X_PC_ALLOC_SIZE_MIN                  = 13
	X_PC_ASYNC_IO                        = 10
	X_PC_CASE_BEHAVIOR                   = 22
	X_PC_CHOWN_RESTRICTED                = 9
	X_PC_FILESIZEBITS                    = 67
	X_PC_LAST                            = 101
	X_PC_LINK_MAX                        = 1
	X_PC_MAX_CANON                       = 2
	X_PC_MAX_INPUT                       = 3
	X_PC_MIN_HOLE_SIZE                   = 21
	X_PC_NAME_MAX                        = 4
	X_PC_NO_TRUNC                        = 7
	X_PC_PATH_MAX                        = 5
	X_PC_PIPE_BUF                        = 6
	X_PC_PRIO_IO                         = 11
	X_PC_REC_INCR_XFER_SIZE              = 14
	X_PC_REC_MAX_XFER_SIZE               = 15
	X_PC_REC_MIN_XFER_SIZE               = 16
	X_PC_REC_XFER_ALIGN                  = 17
	X_PC_SATTR_ENABLED                   = 23
	X_PC_SATTR_EXISTS                    = 24
	X_PC_SYMLINK_MAX                     = 18
	X_PC_SYNC_IO                         = 12
	X_PC_TIMESTAMP_RESOLUTION            = 26
	X_PC_VDISABLE                        = 8
	X_PC_XATTR_ENABLED                   = 100
	X_PC_XATTR_EXISTS                    = 101
	X_POINTER_ALIGNMENT                  = 8
	X_POSIX2_CHAR_TERM                   = 1
	X_POSIX2_C_BIND                      = 1
	X_POSIX2_C_DEV                       = 1
	X_POSIX2_C_VERSION                   = 199209
	X_POSIX2_FORT_RUN                    = 1
	X_POSIX2_LOCALEDEF                   = 1
	X_POSIX2_SW_DEV                      = 1
	X_POSIX2_UPE                         = 1
	X_POSIX2_VERSION                     = 199209
	X_POSIX_REGEXP                       = 1
	X_POSIX_SHELL                        = 1
	X_POSIX_VDISABLE                     = 0
	X_POSIX_VERSION                      = 199506
	X_PSM_MODULES                        = 0
	X_PTRDIFF_T                          = 0
	X_RESTRICT_KYWD                      = 0
	X_RTC_CONFIG                         = 0
	X_RUSAGESYS_GETRUSAGE                = 0
	X_RUSAGESYS_GETRUSAGE_CHLD           = 1
	X_RUSAGESYS_GETRUSAGE_LWP            = 2
	X_RUSAGESYS_GETVMUSAGE               = 3
	X_RWL_MAGIC                          = 0x5257
	X_SA_FAMILY_T                        = 0
	X_SC_2_CHAR_TERM                     = 66
	X_SC_2_C_BIND                        = 45
	X_SC_2_C_DEV                         = 46
	X_SC_2_C_VERSION                     = 47
	X_SC_2_FORT_DEV                      = 48
	X_SC_2_FORT_RUN                      = 49
	X_SC_2_LOCALEDEF                     = 50
	X_SC_2_PBS                           = 724
	X_SC_2_PBS_ACCOUNTING                = 725
	X_SC_2_PBS_CHECKPOINT                = 726
	X_SC_2_PBS_LOCATE                    = 728
	X_SC_2_PBS_MESSAGE                   = 729
	X_SC_2_PBS_TRACK                     = 730
	X_SC_2_SW_DEV                        = 51
	X_SC_2_UPE                           = 52
	X_SC_2_VERSION                       = 53
	X_SC_ADVISORY_INFO                   = 731
	X_SC_AIO_LISTIO_MAX                  = 18
	X_SC_AIO_MAX                         = 19
	X_SC_AIO_PRIO_DELTA_MAX              = 20
	X_SC_ARG_MAX                         = 1
	X_SC_ASYNCHRONOUS_IO                 = 21
	X_SC_ATEXIT_MAX                      = 76
	X_SC_AVPHYS_PAGES                    = 501
	X_SC_BARRIERS                        = 732
	X_SC_BC_BASE_MAX                     = 54
	X_SC_BC_DIM_MAX                      = 55
	X_SC_BC_SCALE_MAX                    = 56
	X_SC_BC_STRING_MAX                   = 57
	X_SC_CHILD_MAX                       = 2
	X_SC_CLK_TCK                         = 3
	X_SC_CLOCK_SELECTION                 = 733
	X_SC_COHER_BLKSZ                     = 503
	X_SC_COLL_WEIGHTS_MAX                = 58
	X_SC_CPUID_MAX                       = 517
	X_SC_CPUTIME                         = 734
	X_SC_DCACHE_ASSOC                    = 513
	X_SC_DCACHE_BLKSZ                    = 510
	X_SC_DCACHE_LINESZ                   = 508
	X_SC_DCACHE_SZ                       = 506
	X_SC_DCACHE_TBLKSZ                   = 511
	X_SC_DELAYTIMER_MAX                  = 22
	X_SC_EPHID_MAX                       = 518
	X_SC_EXPR_NEST_MAX                   = 59
	X_SC_FSYNC                           = 23
	X_SC_GETGR_R_SIZE_MAX                = 569
	X_SC_GETPW_R_SIZE_MAX                = 570
	X_SC_HOST_NAME_MAX                   = 735
	X_SC_ICACHE_ASSOC                    = 512
	X_SC_ICACHE_BLKSZ                    = 509
	X_SC_ICACHE_LINESZ                   = 507
	X_SC_ICACHE_SZ                       = 505
	X_SC_IOV_MAX                         = 77
	X_SC_IPV6                            = 762
	X_SC_JOB_CONTROL                     = 6
	X_SC_LINE_MAX                        = 60
	X_SC_LOGIN_NAME_MAX                  = 571
	X_SC_LOGNAME_MAX                     = 10
	X_SC_MAPPED_FILES                    = 24
	X_SC_MAXPID                          = 514
	X_SC_MEMLOCK                         = 25
	X_SC_MEMLOCK_RANGE                   = 26
	X_SC_MEMORY_PROTECTION               = 27
	X_SC_MESSAGE_PASSING                 = 28
	X_SC_MONOTONIC_CLOCK                 = 736
	X_SC_MQ_OPEN_MAX                     = 29
	X_SC_MQ_PRIO_MAX                     = 30
	X_SC_NGROUPS_MAX                     = 4
	X_SC_NPROCESSORS_CONF                = 14
	X_SC_NPROCESSORS_MAX                 = 516
	X_SC_NPROCESSORS_ONLN                = 15
	X_SC_OPEN_MAX                        = 5
	X_SC_PAGESIZE                        = 11
	X_SC_PAGE_SIZE                       = 11
	X_SC_PASS_MAX                        = 9
	X_SC_PHYS_PAGES                      = 500
	X_SC_PRIORITIZED_IO                  = 31
	X_SC_PRIORITY_SCHEDULING             = 32
	X_SC_RAW_SOCKETS                     = 763
	X_SC_READER_WRITER_LOCKS             = 737
	X_SC_REALTIME_SIGNALS                = 33
	X_SC_REGEXP                          = 738
	X_SC_RE_DUP_MAX                      = 61
	X_SC_RTSIG_MAX                       = 34
	X_SC_SAVED_IDS                       = 7
	X_SC_SEMAPHORES                      = 35
	X_SC_SEM_NSEMS_MAX                   = 36
	X_SC_SEM_VALUE_MAX                   = 37
	X_SC_SHARED_MEMORY_OBJECTS           = 38
	X_SC_SHELL                           = 739
	X_SC_SIGQUEUE_MAX                    = 39
	X_SC_SIGRT_MAX                       = 41
	X_SC_SIGRT_MIN                       = 40
	X_SC_SPAWN                           = 740
	X_SC_SPIN_LOCKS                      = 741
	X_SC_SPLIT_CACHE                     = 504
	X_SC_SPORADIC_SERVER                 = 742
	X_SC_SS_REPL_MAX                     = 743
	X_SC_STACK_PROT                      = 515
	X_SC_STREAM_MAX                      = 16
	X_SC_SYMLOOP_MAX                     = 744
	X_SC_SYNCHRONIZED_IO                 = 42
	X_SC_THREADS                         = 576
	X_SC_THREAD_ATTR_STACKADDR           = 577
	X_SC_THREAD_ATTR_STACKSIZE           = 578
	X_SC_THREAD_CPUTIME                  = 745
	X_SC_THREAD_DESTRUCTOR_ITERATIONS    = 568
	X_SC_THREAD_KEYS_MAX                 = 572
	X_SC_THREAD_PRIORITY_SCHEDULING      = 579
	X_SC_THREAD_PRIO_INHERIT             = 580
	X_SC_THREAD_PRIO_PROTECT             = 581
	X_SC_THREAD_PROCESS_SHARED           = 582
	X_SC_THREAD_SAFE_FUNCTIONS           = 583
	X_SC_THREAD_SPORADIC_SERVER          = 746
	X_SC_THREAD_STACK_MIN                = 573
	X_SC_THREAD_THREADS_MAX              = 574
	X_SC_TIMEOUTS                        = 747
	X_SC_TIMERS                          = 43
	X_SC_TIMER_MAX                       = 44
	X_SC_TRACE                           = 748
	X_SC_TRACE_EVENT_FILTER              = 749
	X_SC_TRACE_EVENT_NAME_MAX            = 750
	X_SC_TRACE_INHERIT                   = 751
	X_SC_TRACE_LOG                       = 752
	X_SC_TRACE_NAME_MAX                  = 753
	X_SC_TRACE_SYS_MAX                   = 754
	X_SC_TRACE_USER_EVENT_MAX            = 755
	X_SC_TTY_NAME_MAX                    = 575
	X_SC_TYPED_MEMORY_OBJECTS            = 756
	X_SC_TZNAME_MAX                      = 17
	X_SC_T_IOV_MAX                       = 79
	X_SC_UADDR_MAX                       = 519
	X_SC_V6_ILP32_OFF32                  = 757
	X_SC_V6_ILP32_OFFBIG                 = 758
	X_SC_V6_LP64_OFF64                   = 759
	X_SC_V6_LPBIG_OFFBIG                 = 760
	X_SC_VERSION                         = 8
	X_SC_XBS5_ILP32_OFF32                = 720
	X_SC_XBS5_ILP32_OFFBIG               = 721
	X_SC_XBS5_LP64_OFF64                 = 722
	X_SC_XBS5_LPBIG_OFFBIG               = 723
	X_SC_XOPEN_CRYPT                     = 62
	X_SC_XOPEN_ENH_I18N                  = 63
	X_SC_XOPEN_LEGACY                    = 717
	X_SC_XOPEN_REALTIME                  = 718
	X_SC_XOPEN_REALTIME_THREADS          = 719
	X_SC_XOPEN_SHM                       = 64
	X_SC_XOPEN_STREAMS                   = 761
	X_SC_XOPEN_UNIX                      = 78
	X_SC_XOPEN_VERSION                   = 12
	X_SC_XOPEN_XCU_VERSION               = 67
	X_SEMA_MAGIC                         = 0x534d
	X_SHORT_ALIGNMENT                    = 2
	X_SIGEVENT                           = 0
	X_SIGSET_T                           = 0
	X_SIGVAL                             = 0
	X_SIZE_T                             = 0
	X_SOCKLEN_T                          = 0
	X_SOFT_HOSTID                        = 0
	X_SSIZE_T                            = 0
	X_SS_MAXSIZE                         = 256
	X_STACK_GROWS_DOWNWARD               = 0
	X_STDC_C11                           = 0
	X_STDC_C99                           = 0
	X_SUNOS_VTOC_16                      = 0
	X_SUSECONDS_T                        = 0
	X_SYS_BYTEORDER_H                    = 0
	X_SYS_CCOMPILE_H                     = 0
	X_SYS_CONDVAR_H                      = 0
	X_SYS_CRED_H                         = 0
	X_SYS_FEATURE_TESTS_H                = 0
	X_SYS_INT_TYPES_H                    = 0
	X_SYS_ISA_DEFS_H                     = 0
	X_SYS_KMEM_H                         = 0
	X_SYS_KSTAT_H                        = 0
	X_SYS_KSYNCH_H                       = 0
	X_SYS_LIST_H                         = 0
	X_SYS_LIST_IMPL_H                    = 0
	X_SYS_MACHLOCK_H                     = 0
	X_SYS_MACHTYPES_H                    = 0
	X_SYS_MUTEX_H                        = 0
	X_SYS_NULL_H                         = 0
	X_SYS_PARAM_H                        = 0
	X_SYS_REFSTR_H                       = 0
	X_SYS_RESOURCE_H                     = 0
	X_SYS_RWLOCK_H                       = 0
	X_SYS_RWSTLOCK_H                     = 0
	X_SYS_SELECT_H                       = 0
	X_SYS_SEMAPHORE_H                    = 0
	X_SYS_SOCKET_IMPL_H                  = 0
	X_SYS_STATVFS_H                      = 0
	X_SYS_TIME_H                         = 0
	X_SYS_TIME_IMPL_H                    = 0
	X_SYS_TSOL_LABEL_H                   = 0
	X_SYS_TYPES_H                        = 0
	X_SYS_T_LOCK_H                       = 0
	X_SYS_UADMIN_H                       = 0
	X_SYS_UIO_H                          = 0
	X_SYS_UNISTD_H                       = 0
	X_SYS_UN_H                           = 0
	X_SYS_VFS_H                          = 0
	X_SYS_VMEM_H                         = 0
	X_SYS_VNODE_H                        = 0
	X_SYS_ZONE_H                         = 0
	X_TIMER_T                            = 0
	X_TIME_H                             = 0
	X_TIME_T                             = 0
	X_TTY_BUFSIZ                         = 2048
	X_UID_T                              = 0
	X_VM_SEG_ENUM_H                      = 0
	X_XOPEN_ENH_I18N                     = 1
	X_XOPEN_REALTIME                     = 1
	X_XOPEN_SHM                          = 1
	X_XOPEN_STREAMS                      = 1
	X_XOPEN_UNIX                         = 0
	X_XOPEN_VERSION                      = 3
	X_XOPEN_XCU_VERSION                  = 4
	X_XOPEN_XPG3                         = 0
	X_XOPEN_XPG4                         = 0
	Sun                                  = 1
	Unix                                 = 1
)

const (
	CV_DEFAULT = 0
	CV_DRIVER  = 1
)

const (
	KMEM_CBRC_YES       = 0
	KMEM_CBRC_NO        = 1
	KMEM_CBRC_LATER     = 2
	KMEM_CBRC_DONT_NEED = 3
	KMEM_CBRC_DONT_KNOW = 4
)

const (
	MUTEX_ADAPTIVE = 0
	MUTEX_SPIN     = 1
	MUTEX_DRIVER   = 4
	MUTEX_DEFAULT  = 6
)

const (
	RW_DRIVER  = 2
	RW_DEFAULT = 4
)

const (
	RW_WRITER              = 0
	RW_READER              = 1
	RW_READER_STARVEWRITER = 2
)

const (
	SEMA_DEFAULT = 0
	SEMA_DRIVER  = 1
)

const (
	B_FALSE   = 0
	B_TRUE    = 1
	X_B_FALSE = 0
	X_B_TRUE  = 1
)

const (
	UIOTYPE_ASYNCIO  = 0
	UIOTYPE_ZEROCOPY = 1
	UIOTYPE_PEEKSIZE = 2
)

const (
	UIO_READ  = 0
	UIO_WRITE = 1
)

const (
	UIO_USERSPACE  = 0
	UIO_SYSSPACE   = 1
	UIO_USERISPACE = 2
)

const (
	ROOT_INIT    = 0
	ROOT_REMOUNT = 1
	ROOT_UNMOUNT = 2
)

const (
	VNTRANS_EXISTS    = 0
	VNTRANS_IDLED     = 1
	VNTRANS_RECLAIMED = 2
	VNTRANS_DESTROYED = 3
)

const (
	VFSDEF_VERSION = 5
)

const (
	VNON  = 0
	VREG  = 1
	VDIR  = 2
	VBLK  = 3
	VCHR  = 4
	VLNK  = 5
	VFIFO = 6
	VDOOR = 7
	VPROC = 8
	VSOCK = 9
	VPORT = 10
	VBAD  = 11
)

const (
	RMFILE      = 0
	RMDIRECTORY = 1
)
const (
	NO_FOLLOW = 0
	FOLLOW    = 1
)
const (
	NONEXCL = 0
	EXCL    = 1
)
const (
	CRCREAT = 0
	CRMKNOD = 1
	CRMKDIR = 2
)

const (
	VE_SUPPORT             = 0
	VE_RENAME_SRC          = 1
	VE_RENAME_DEST         = 2
	VE_REMOVE              = 3
	VE_RMDIR               = 4
	VE_CREATE              = 5
	VE_LINK                = 6
	VE_RENAME_DEST_DIR     = 7
	VE_MOUNTEDOVER         = 8
	VE_TRUNCATE            = 9
	VE_PRE_RENAME_SRC      = 10
	VE_PRE_RENAME_DEST     = 11
	VE_PRE_RENAME_DEST_DIR = 12
	VE_RENAME_SRC_DIR      = 13
	VE_RESIZE              = 14
)

const (
	V_READ    = 0
	V_WRITE   = 1
	V_RDORWR  = 2
	V_RDANDWR = 3
)

const (
	ZONE_IS_UNINITIALIZED = 0
	ZONE_IS_INITIALIZED   = 1
	ZONE_IS_READY         = 2
	ZONE_IS_BOOTING       = 3
	ZONE_IS_RUNNING       = 4
	ZONE_IS_SHUTTING_DOWN = 5
	ZONE_IS_EMPTY         = 6
	ZONE_IS_DOWN          = 7
	ZONE_IS_DYING         = 8
	ZONE_IS_DEAD          = 9
)

const (
	Z_READY             = 0
	Z_BOOT              = 1
	Z_FORCEBOOT         = 2
	Z_REBOOT            = 3
	Z_HALT              = 4
	Z_NOTE_UNINSTALLING = 5
	Z_MOUNT             = 6
	Z_FORCEMOUNT        = 7
	Z_UNMOUNT           = 8
	Z_SHUTDOWN          = 9
)

const (
	F_INVAL      = 0
	F_PROT       = 1
	F_SOFTLOCK   = 2
	F_SOFTUNLOCK = 3
)

const (
	L_PAGELOCK   = 0
	L_PAGEUNLOCK = 1
)

const (
	S_OTHER      = 0
	S_READ       = 1
	S_WRITE      = 2
	S_EXEC       = 3
	S_CREATE     = 4
	S_READ_NOCOW = 5
)

const (
	S_CAPABILITY_NOMINFLT = 0
)

type Ptrdiff_t = int64

type Size_t = uint64

type Wchar_t = int32

type X__int128_t = struct {
	Flo int64
	Fhi int64
}
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
}

type X__builtin_va_list = uintptr
type X__float128 = float64

type X_label_t = struct{ Fval [8]int64 }

type Label_t = X_label_t

type Lock_t = uint8

type Int8_t = int8
type Int16_t = int16
type Int32_t = int32
type Int64_t = int64

type Uint8_t = uint8
type Uint16_t = uint16
type Uint32_t = uint32
type Uint64_t = uint64

type Intmax_t = int64
type Uintmax_t = uint64

type Intptr_t = int64
type Uintptr_t = uint64

type Int_fast8_t = int8
type Int_fast16_t = int32
type Int_fast32_t = int32
type Int_fast64_t = int64

type Uint_fast8_t = uint8
type Uint_fast16_t = uint32
type Uint_fast32_t = uint32
type Uint_fast64_t = uint64

type Int_least8_t = int8
type Int_least16_t = int16
type Int_least32_t = int32
type Int_least64_t = int64

type Uint_least8_t = uint8
type Uint_least16_t = uint16
type Uint_least32_t = uint32
type Uint_least64_t = uint64

type Longlong_t = int64
type U_longlong_t = uint64

type T_scalar_t = int32
type T_uscalar_t = uint32

type Uchar_t = uint8
type Ushort_t = uint16
type Uint_t = uint32
type Ulong_t = uint64

type Caddr_t = uintptr
type Daddr_t = int64
type Cnt_t = int16

type Pfn_t = uint64
type Pgcnt_t = uint64
type Spgcnt_t = int64

type Use_t = uint8
type Sysid_t = int16
type Index_t = int16
type Timeout_id_t = uintptr
type Bufcall_id_t = uintptr

type Off_t = int64

type Off64_t = int64

type Ino_t = uint64
type Blkcnt_t = int64
type Fsblkcnt_t = uint64
type Fsfilcnt_t = uint64

type Ino64_t = uint64
type Blkcnt64_t = int64
type Fsblkcnt64_t = uint64
type Fsfilcnt64_t = uint64

type Blksize_t = int32

type Boolean_t = uint32

type Pad64_t = int64
type Upad64_t = uint64

type Pad128_t = struct {
	F_q          float64
	F__ccgo_pad1 [8]byte
}

type Upad128_t = struct {
	F_q          float64
	F__ccgo_pad1 [8]byte
}

type Offset_t = int64
type U_offset_t = uint64
type Len_t = uint64
type Diskaddr_t = uint64

type Lloff_t = struct{ F_f int64 }

type Lldaddr_t = struct{ F_f int64 }

type K_fltset_t = uint32

type Id_t = int32

type Lgrp_id_t = int32

type Useconds_t = uint32

type Suseconds_t = int64

type Major_t = uint32
type Minor_t = uint32

type Pri_t = int16

type Cpu_flag_t = uint16

type O_mode_t = uint16
type O_dev_t = int16
type O_uid_t = uint16
type O_gid_t = uint16
type O_nlink_t = int16
type O_pid_t = int16
type O_ino_t = uint16

type Key_t = int32
type Mode_t = uint32

type Uid_t = uint32

type Gid_t = uint32

type Datalink_id_t = uint32
type Vrid_t = uint32

type Taskid_t = int32
type Projid_t = int32
type Poolid_t = int32
type Zoneid_t = int32
type Ctid_t = int32

type Pthread_t = uint32
type Pthread_key_t = uint32

type X_pthread_mutex = struct {
	F__pthread_mutex_flags struct {
		F__pthread_mutex_flag1   uint16
		F__pthread_mutex_flag2   uint8
		F__pthread_mutex_ceiling uint8
		F__pthread_mutex_type    uint16
		F__pthread_mutex_magic   uint16
	}
	F__pthread_mutex_lock struct {
		F__ccgo_pad1            [0]uint64
		F__pthread_mutex_lock64 struct{ F__pthread_mutex_pad [8]uint8 }
	}
	F__pthread_mutex_data uint64
}

type Pthread_mutex_t = X_pthread_mutex

type X_pthread_cond = struct {
	F__pthread_cond_flags struct {
		F__pthread_cond_flag  [4]uint8
		F__pthread_cond_type  uint16
		F__pthread_cond_magic uint16
	}
	F__pthread_cond_data uint64
}

type Pthread_cond_t = X_pthread_cond

type X_pthread_rwlock = struct {
	F__pthread_rwlock_readers  int32
	F__pthread_rwlock_type     uint16
	F__pthread_rwlock_magic    uint16
	F__pthread_rwlock_mutex    Pthread_mutex_t
	F__pthread_rwlock_readercv Pthread_cond_t
	F__pthread_rwlock_writercv Pthread_cond_t
}

type Pthread_rwlock_t = X_pthread_rwlock

type Pthread_barrier_t = struct {
	F__pthread_barrier_count    uint32
	F__pthread_barrier_current  uint32
	F__pthread_barrier_cycle    uint64
	F__pthread_barrier_reserved uint64
	F__pthread_barrier_lock     Pthread_mutex_t
	F__pthread_barrier_cond     Pthread_cond_t
}

type Pthread_spinlock_t = Pthread_mutex_t

type X_pthread_attr = struct{ F__pthread_attrp uintptr }

type Pthread_attr_t = X_pthread_attr

type X_pthread_mutexattr = struct{ F__pthread_mutexattrp uintptr }

type Pthread_mutexattr_t = X_pthread_mutexattr

type X_pthread_condattr = struct{ F__pthread_condattrp uintptr }

type Pthread_condattr_t = X_pthread_condattr

type X_once = struct{ F__pthread_once_pad [4]uint64 }

type Pthread_once_t = X_once

type X_pthread_rwlockattr = struct{ F__pthread_rwlockattrp uintptr }

type Pthread_rwlockattr_t = X_pthread_rwlockattr

type Pthread_barrierattr_t = struct{ F__pthread_barrierattrp uintptr }

type Dev_t = uint64

type Nlink_t = uint32
type Pid_t = int32

type Ssize_t = int64

type Time_t = int64

type Clock_t = int64

type Clockid_t = int32

type Timer_t = int32

type Unchar = uint8
type Ushort = uint16
type Uint = uint32
type Ulong = uint64

type U_char = uint8
type U_short = uint16
type U_int = uint32
type U_long = uint64
type X_quad = struct{ Fval [2]int32 }

type Quad_t = X_quad
type Quad = Quad_t

type Timespec = struct {
	Ftv_sec  int64
	Ftv_nsec int64
}

type Timespec_t = Timespec

type Timestruc_t = Timespec

type Itimerspec = struct {
	Fit_interval struct {
		Ftv_sec  int64
		Ftv_nsec int64
	}
	Fit_value struct {
		Ftv_sec  int64
		Ftv_nsec int64
	}
}

type Itimerspec_t = Itimerspec

type Timeval = struct {
	Ftv_sec  int64
	Ftv_usec int64
}

type Timezone = struct {
	Ftz_minuteswest int32
	Ftz_dsttime     int32
}

type Itimerval = struct {
	Fit_interval struct {
		Ftv_sec  int64
		Ftv_usec int64
	}
	Fit_value struct {
		Ftv_sec  int64
		Ftv_usec int64
	}
}

type Hrtime_t = int64

type Tm = struct {
	Ftm_sec   int32
	Ftm_min   int32
	Ftm_hour  int32
	Ftm_mday  int32
	Ftm_mon   int32
	Ftm_year  int32
	Ftm_wday  int32
	Ftm_yday  int32
	Ftm_isdst int32
}

type Sigval = struct {
	F__ccgo_pad1 [0]uint64
	Fsival_int   int32
	F__ccgo_pad2 [4]byte
}

type Sigevent = struct {
	Fsigev_notify int32
	Fsigev_signo  int32
	Fsigev_value  struct {
		F__ccgo_pad1 [0]uint64
		Fsival_int   int32
		F__ccgo_pad2 [4]byte
	}
	Fsigev_notify_function   uintptr
	Fsigev_notify_attributes uintptr
	F__sigev_pad2            int32
	F__ccgo_pad1             [4]byte
}

type Locale_t = uintptr

type Sigset_t = struct{ F__sigbits [4]uint32 }

type Fd_mask = int64
type Fds_mask = int64

type Fd_set1 = struct{ Ffds_bits [1024]int64 }

type Fd_set = Fd_set1

type X_tsol_binary_level_lrange = struct {
	Flower_bound uintptr
	Fupper_bound uintptr
}

type M_range_t = X_tsol_binary_level_lrange

type Blrange_t = M_range_t

type Tsol_mlp_s = struct {
	Fmlp_ipp        uint8
	F__ccgo_pad1    [1]byte
	Fmlp_port       uint16
	Fmlp_port_upper uint16
}

type Tsol_mlp_t = Tsol_mlp_s

type Sa_family_t = uint16

type Sockaddr = struct {
	Fsa_family uint16
	Fsa_data   [14]int8
}

type Sockaddr_un = struct {
	Fsun_family uint16
	Fsun_path   [108]int8
}

type Sockaddr_dl = struct {
	Fsdl_family uint16
	Fsdl_index  uint16
	Fsdl_type   uint8
	Fsdl_nlen   uint8
	Fsdl_alen   uint8
	Fsdl_slen   uint8
	Fsdl_data   [244]int8
}

type Sockaddr_maxalign_t = float64

type Sockaddr_storage = struct {
	Fss_family uint16
	F_ss_pad1  [6]int8
	F_ss_align float64
	F_ss_pad2  [240]int8
}

type Sockaddr_ll = struct {
	Fsll_family   uint16
	Fsll_protocol uint16
	Fsll_ifindex  int32
	Fsll_hatype   uint16
	Fsll_pkttype  uint8
	Fsll_halen    uint8
	Fsll_addr     [8]uint8
}

type Socklen_t = uint32

type Psocklen_t = uintptr

type In_port_t = uint16

type In_addr_t = uint32

type Ipaddr_t = uint32

type In6_addr = struct {
	F_S6_un struct {
		F__ccgo_pad1 [0]uint32
		F_S6_u8      [16]uint8
	}
}

type In6_addr_t = In6_addr

type In_addr = struct {
	FS_un struct {
		F__ccgo_pad1 [0]uint32
		FS_un_b      struct {
			Fs_b1 uint8
			Fs_b2 uint8
			Fs_b3 uint8
			Fs_b4 uint8
		}
	}
}

type Sockaddr_in = struct {
	Fsin_family uint16
	Fsin_port   uint16
	Fsin_addr   struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
	Fsin_zero [8]int8
}

type Sockaddr_in6 = struct {
	Fsin6_family   uint16
	Fsin6_port     uint16
	Fsin6_flowinfo uint32
	Fsin6_addr     struct {
		F_S6_un struct {
			F__ccgo_pad1 [0]uint32
			F_S6_u8      [16]uint8
		}
	}
	Fsin6_scope_id uint32
	F__sin6_src_id uint32
}

type Ipsec_req = struct {
	Fipsr_ah_req         uint32
	Fipsr_esp_req        uint32
	Fipsr_self_encap_req uint32
	Fipsr_auth_alg       uint8
	Fipsr_esp_alg        uint8
	Fipsr_esp_auth_alg   uint8
	F__ccgo_pad1         [1]byte
}

type Ipsec_req_t = Ipsec_req

type Ip_mreq = struct {
	Fimr_multiaddr struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
	Fimr_interface struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
}

type Ip_mreq_source = struct {
	Fimr_multiaddr struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
	Fimr_sourceaddr struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
	Fimr_interface struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
}

type Ipv6_mreq = struct {
	Fipv6mr_multiaddr struct {
		F_S6_un struct {
			F__ccgo_pad1 [0]uint32
			F_S6_u8      [16]uint8
		}
	}
	Fipv6mr_interface uint32
}

type Group_req = struct {
	Fgr_interface uint32
	F__ccgo_pad1  [4]byte
	Fgr_group     struct {
		Fss_family uint16
		F_ss_pad1  [6]int8
		F_ss_align float64
		F_ss_pad2  [240]int8
	}
}

type Group_source_req = struct {
	Fgsr_interface uint32
	F__ccgo_pad1   [4]byte
	Fgsr_group     struct {
		Fss_family uint16
		F_ss_pad1  [6]int8
		F_ss_align float64
		F_ss_pad2  [240]int8
	}
	Fgsr_source struct {
		Fss_family uint16
		F_ss_pad1  [6]int8
		F_ss_align float64
		F_ss_pad2  [240]int8
	}
}

type Group_filter = struct {
	Fgf_interface uint32
	F__ccgo_pad1  [4]byte
	Fgf_group     struct {
		Fss_family uint16
		F_ss_pad1  [6]int8
		F_ss_align float64
		F_ss_pad2  [240]int8
	}
	Fgf_fmode  uint32
	Fgf_numsrc uint32
	Fgf_slist  [1]struct {
		Fss_family uint16
		F_ss_pad1  [6]int8
		F_ss_align float64
		F_ss_pad2  [240]int8
	}
}

type Ip_msfilter = struct {
	Fimsf_multiaddr struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
	Fimsf_interface struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
	Fimsf_fmode  uint32
	Fimsf_numsrc uint32
	Fimsf_slist  [1]struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
}

type In_pktinfo = struct {
	Fipi_ifindex  uint32
	Fipi_spec_dst struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
	Fipi_addr struct {
		FS_un struct {
			F__ccgo_pad1 [0]uint32
			FS_un_b      struct {
				Fs_b1 uint8
				Fs_b2 uint8
				Fs_b3 uint8
				Fs_b4 uint8
			}
		}
	}
}

type In_pktinfo_t = In_pktinfo

type In6_pktinfo = struct {
	Fipi6_addr struct {
		F_S6_un struct {
			F__ccgo_pad1 [0]uint32
			F_S6_u8      [16]uint8
		}
	}
	Fipi6_ifindex uint32
}

type Ip6_mtuinfo = struct {
	Fip6m_addr struct {
		Fsin6_family   uint16
		Fsin6_port     uint16
		Fsin6_flowinfo uint32
		Fsin6_addr     struct {
			F_S6_un struct {
				F__ccgo_pad1 [0]uint32
				F_S6_u8      [16]uint8
			}
		}
		Fsin6_scope_id uint32
		F__sin6_src_id uint32
	}
	Fip6m_mtu uint32
}

type In_prefix_t = struct {
	Fin_prefix_addr In_addr
	Fin_prefix_len  uint32
}

type Zone_def = struct {
	Fzone_name      uintptr
	Fzone_root      uintptr
	Fzone_privs     uintptr
	Fzone_privssz   uint64
	Frctlbuf        uintptr
	Frctlbufsz      uint64
	Fextended_error uintptr
	Fzfsbuf         uintptr
	Fzfsbufsz       uint64
	Fmatch          int32
	Fdoi            uint32
	Flabel          uintptr
	Fflags          int32
	Fzoneid         int32
}

type Zone_status_t = uint32

type Zone_cmd_t = uint32

type Zone_cmd_arg = struct {
	Funiqid  uint64
	Fcmd     uint32
	Fstatus  int32
	Fdebug   uint32
	Flocale  [1024]int8
	Fbootbuf [256]int8
	Fpad     int32
}

type Zone_cmd_arg_t = Zone_cmd_arg

type Zone_cmd_rval = struct {
	Frval        int32
	Ferrbuf      [1]int8
	F__ccgo_pad1 [3]byte
}

type Zone_cmd_rval_t = Zone_cmd_rval

type Zone_net_data = struct {
	Fzn_type     int32
	Fzn_len      int32
	Fzn_linkid   uint32
	Fzn_val      [1]uint8
	F__ccgo_pad1 [3]byte
}

type Zone_net_data_t = Zone_net_data

type Disp_lock_t = uint8

type Kmutex_type_t = uint32

type Mutex = struct{ F_opaque [1]uintptr }

type Kmutex_t = Mutex

type Krw_type_t = uint32

type Krw_t = uint32

type X_krwlock = struct{ F_opaque [1]uintptr }

type Krwlock_t = X_krwlock

type Ksema_type_t = uint32

type X_ksema = struct{ F_opaque [2]uintptr }

type Ksema_t = X_ksema

type X_kcondvar = struct{ F_opaque uint16 }

type Kcondvar_t = X_kcondvar

type Kcv_type_t = uint32

type Rwstlock = struct {
	Frwst_count  int64
	Frwst_rcv    Kcondvar_t
	Frwst_wcv    Kcondvar_t
	F__ccgo_pad1 [4]byte
	Frwst_lock   Kmutex_t
}

type Rwstlock_t = Rwstlock

type Iovec = struct {
	Fiov_base uintptr
	Fiov_len  uint64
}

type Iovec_t = Iovec

type Uio_seg_t = uint32

type Uio = struct {
	Fuio_iov     uintptr
	Fuio_iovcnt  int32
	F__ccgo_pad1 [4]byte
	F_uio_offset Lloff_t
	Fuio_segflg  uint32
	Fuio_fmode   uint16
	Fuio_extflg  uint16
	F_uio_limit  Lloff_t
	Fuio_resid   int64
}

type Uio_t = Uio

type Uioa_page_s = struct {
	Fuioa_pfncnt int32
	F__ccgo_pad1 [4]byte
	Fuioa_ppp    uintptr
	Fuioa_base   uintptr
	Fuioa_len    uint64
}

type Uioa_page_t = Uioa_page_s

type Uioa_s = struct {
	Fuio_iov     uintptr
	Fuio_iovcnt  int32
	F__ccgo_pad1 [4]byte
	F_uio_offset Lloff_t
	Fuio_segflg  uint32
	Fuio_fmode   uint16
	Fuio_extflg  uint16
	F_uio_limit  Lloff_t
	Fuio_resid   int64
	Fuioa_state  uint32
	F__ccgo_pad2 [4]byte
	Fuioa_mbytes int64
	Fuioa_lcur   uintptr
	Fuioa_lppp   uintptr
	Fuioa_hwst   [4]uintptr
	Fuioa_locked [16]Uioa_page_t
}

type Uioa_t = Uioa_s

type Xuio_type_t = uint32

type Xuio = struct {
	Fxu_uio      Uio_t
	Fxu_type     uint32
	F__ccgo_pad1 [4]byte
	Fxu_ext      struct {
		Fxu_aio struct {
			Fxu_a_state  uint32
			F__ccgo_pad1 [4]byte
			Fxu_a_mbytes int64
			Fxu_a_lcur   uintptr
			Fxu_a_lppp   uintptr
			Fxu_a_hwst   [4]uintptr
			Fxu_a_locked [16]Uioa_page_t
		}
	}
}

type Xuio_t = Xuio

type Uio_rw_t = uint32

type Uioasync_s = struct {
	Fenabled     uint32
	F__ccgo_pad1 [4]byte
	Fmincnt      uint64
}

type Uioasync_t = Uioasync_s

type Rlim_t = uint64

type Rlimit = struct {
	Frlim_cur uint64
	Frlim_max uint64
}

type Rlim64_t = uint64

type Rlimit64 = struct {
	Frlim_cur uint64
	Frlim_max uint64
}

type Rusage = struct {
	Fru_utime struct {
		Ftv_sec  int64
		Ftv_usec int64
	}
	Fru_stime struct {
		Ftv_sec  int64
		Ftv_usec int64
	}
	Fru_maxrss   int64
	Fru_ixrss    int64
	Fru_idrss    int64
	Fru_isrss    int64
	Fru_minflt   int64
	Fru_majflt   int64
	Fru_nswap    int64
	Fru_inblock  int64
	Fru_oublock  int64
	Fru_msgsnd   int64
	Fru_msgrcv   int64
	Fru_nsignals int64
	Fru_nvcsw    int64
	Fru_nivcsw   int64
}

type Segcapability_t = uint32

type Kid_t = int32

type Kstat = struct {
	Fks_crtime    int64
	Fks_next      uintptr
	Fks_kid       int32
	Fks_module    [31]int8
	Fks_resv      uint8
	Fks_instance  int32
	Fks_name      [31]int8
	Fks_type      uint8
	Fks_class     [31]int8
	Fks_flags     uint8
	Fks_data      uintptr
	Fks_ndata     uint32
	F__ccgo_pad1  [4]byte
	Fks_data_size uint64
	Fks_snaptime  int64
	Fks_update    uintptr
	Fks_private   uintptr
	Fks_snapshot  uintptr
	Fks_lock      uintptr
}

type Kstat_t = Kstat

type Kstat_named = struct {
	Fname      [31]int8
	Fdata_type uint8
	Fvalue     struct {
		F__ccgo_pad1 [0]uint64
		Fc           [16]int8
	}
}

type Kstat_named_t = Kstat_named

type Kstat_intr = struct{ Fintrs [5]uint32 }

type Kstat_intr_t = Kstat_intr

type Kstat_io = struct {
	Fnread       uint64
	Fnwritten    uint64
	Freads       uint32
	Fwrites      uint32
	Fwtime       int64
	Fwlentime    int64
	Fwlastupdate int64
	Frtime       int64
	Frlentime    int64
	Frlastupdate int64
	Fwcnt        uint32
	Frcnt        uint32
}

type Kstat_io_t = Kstat_io

type Kstat_timer = struct {
	Fname         [31]int8
	Fresv         uint8
	Fnum_events   uint64
	Felapsed_time int64
	Fmin_time     int64
	Fmax_time     int64
	Fstart_time   int64
	Fstop_time    int64
}

type Kstat_timer_t = Kstat_timer

type Kmem_cbrc_t = uint32

type List_node = struct {
	Flist_next uintptr
	Flist_prev uintptr
}

type List = struct {
	Flist_size   uint64
	Flist_offset uint64
	Flist_head   struct {
		Flist_next uintptr
		Flist_prev uintptr
	}
}

type List_node_t = List_node
type List_t = List

type Vopstats = struct {
	Fnopen         Kstat_named_t
	Fnclose        Kstat_named_t
	Fnread         Kstat_named_t
	Fread_bytes    Kstat_named_t
	Fnwrite        Kstat_named_t
	Fwrite_bytes   Kstat_named_t
	Fnioctl        Kstat_named_t
	Fnsetfl        Kstat_named_t
	Fngetattr      Kstat_named_t
	Fnsetattr      Kstat_named_t
	Fnaccess       Kstat_named_t
	Fnlookup       Kstat_named_t
	Fncreate       Kstat_named_t
	Fnremove       Kstat_named_t
	Fnlink         Kstat_named_t
	Fnrename       Kstat_named_t
	Fnmkdir        Kstat_named_t
	Fnrmdir        Kstat_named_t
	Fnreaddir      Kstat_named_t
	Freaddir_bytes Kstat_named_t
	Fnsymlink      Kstat_named_t
	Fnreadlink     Kstat_named_t
	Fnfsync        Kstat_named_t
	Fninactive     Kstat_named_t
	Fnfid          Kstat_named_t
	Fnrwlock       Kstat_named_t
	Fnrwunlock     Kstat_named_t
	Fnseek         Kstat_named_t
	Fncmp          Kstat_named_t
	Fnfrlock       Kstat_named_t
	Fnspace        Kstat_named_t
	Fnrealvp       Kstat_named_t
	Fngetpage      Kstat_named_t
	Fnputpage      Kstat_named_t
	Fnmap          Kstat_named_t
	Fnaddmap       Kstat_named_t
	Fndelmap       Kstat_named_t
	Fnpoll         Kstat_named_t
	Fndump         Kstat_named_t
	Fnpathconf     Kstat_named_t
	Fnpageio       Kstat_named_t
	Fndumpctl      Kstat_named_t
	Fndispose      Kstat_named_t
	Fnsetsecattr   Kstat_named_t
	Fngetsecattr   Kstat_named_t
	Fnshrlock      Kstat_named_t
	Fnvnevent      Kstat_named_t
	Fnreqzcbuf     Kstat_named_t
	Fnretzcbuf     Kstat_named_t
}

type Vopstats_t = Vopstats

type Vtype_t = uint32

type Vsd_node = struct {
	Fvs_nodes    List_node_t
	Fvs_nkeys    uint32
	F__ccgo_pad1 [4]byte
	Fvs_value    uintptr
}

type Vnode = struct {
	Fv_lock           Kmutex_t
	Fv_flag           uint32
	Fv_count          uint32
	Fv_phantom_count  uint32
	F__ccgo_pad1      [4]byte
	Fv_data           uintptr
	Fv_vfsp           uintptr
	Fv_stream         uintptr
	Fv_type           uint32
	F__ccgo_pad2      [4]byte
	Fv_rdev           uint64
	Fv_vfsmountedhere uintptr
	Fv_op             uintptr
	Fv_pages          uintptr
	Fv_filocks        uintptr
	Fv_shrlocks       uintptr
	Fv_nbllock        Krwlock_t
	Fv_cv             Kcondvar_t
	F__ccgo_pad3      [6]byte
	Fv_locality       uintptr
	Fv_femhead        uintptr
	Fv_path           uintptr
	Fv_path_stamp     int64
	Fv_rdcnt          uint32
	Fv_wrcnt          uint32
	Fv_mmap_read      uint64
	Fv_mmap_write     uint64
	Fv_mpssdata       uintptr
	Fv_fopdata        uintptr
	Fv_vsd_lock       Kmutex_t
	Fv_vsd            uintptr
	Fv_xattrdir       uintptr
	Fv_count_dnlc     uint32
	F__ccgo_pad4      [4]byte
}

type Vfs = struct {
	Fvfs_next         uintptr
	Fvfs_prev         uintptr
	Fvfs_op           uintptr
	Fvfs_vnodecovered uintptr
	Fvfs_flag         uint32
	Fvfs_bsize        uint32
	Fvfs_fstype       int32
	Fvfs_fsid         Fsid_t
	F__ccgo_pad1      [4]byte
	Fvfs_data         uintptr
	Fvfs_dev          uint64
	Fvfs_bcount       uint64
	Fvfs_list         uintptr
	Fvfs_hash         uintptr
	Fvfs_reflock      Ksema_t
	Fvfs_count        uint32
	F__ccgo_pad2      [4]byte
	Fvfs_mntopts      Mntopts_t
	Fvfs_resource     uintptr
	Fvfs_mntpt        uintptr
	Fvfs_mtime        int64
	Fvfs_implp        uintptr
	Fvfs_zone         uintptr
	Fvfs_zone_next    uintptr
	Fvfs_zone_prev    uintptr
	Fvfs_femhead      uintptr
	Fvfs_lofi_id      uint32
	F__ccgo_pad3      [4]byte
}

type Vnode_t = Vnode

type Vattr = struct {
	Fva_mask     uint32
	Fva_type     uint32
	Fva_mode     uint32
	Fva_uid      uint32
	Fva_gid      uint32
	F__ccgo_pad1 [4]byte
	Fva_fsid     uint64
	Fva_nodeid   uint64
	Fva_nlink    uint32
	F__ccgo_pad2 [4]byte
	Fva_size     uint64
	Fva_atime    Timestruc_t
	Fva_mtime    Timestruc_t
	Fva_ctime    Timestruc_t
	Fva_rdev     uint64
	Fva_blksize  uint32
	F__ccgo_pad3 [4]byte
	Fva_nblocks  uint64
	Fva_seq      uint32
	F__ccgo_pad4 [4]byte
}

type Vattr_t = Vattr

type Xoptattr = struct {
	Fxoa_createtime     Timestruc_t
	Fxoa_archive        uint8
	Fxoa_system         uint8
	Fxoa_readonly       uint8
	Fxoa_hidden         uint8
	Fxoa_nounlink       uint8
	Fxoa_immutable      uint8
	Fxoa_appendonly     uint8
	Fxoa_nodump         uint8
	Fxoa_opaque         uint8
	Fxoa_av_quarantined uint8
	Fxoa_av_modified    uint8
	Fxoa_av_scanstamp   [32]uint8
	Fxoa_reparse        uint8
	F__ccgo_pad1        [4]byte
	Fxoa_generation     uint64
	Fxoa_offline        uint8
	Fxoa_sparse         uint8
	Fxoa_projinherit    uint8
	F__ccgo_pad2        [5]byte
	Fxoa_projid         uint64
}

type Xoptattr_t = Xoptattr

type Xvattr = struct {
	Fxva_vattr       Vattr_t
	Fxva_magic       uint32
	Fxva_mapsize     uint32
	Fxva_rtnattrmapp uintptr
	Fxva_reqattrmap  [3]uint32
	Fxva_rtnattrmap  [3]uint32
	Fxva_xoptattrs   Xoptattr_t
}

type Xvattr_t = Xvattr

type Vattr32_t = Vattr_t

type Rm_t = uint32
type Symfollow_t = uint32
type Vcexcl_t = uint32
type Create_t = uint32

type Vnevent_t = uint32

type V_mode_t = uint32

type Vsecattr = struct {
	Fvsa_mask      uint32
	Fvsa_aclcnt    int32
	Fvsa_aclentp   uintptr
	Fvsa_dfaclcnt  int32
	F__ccgo_pad1   [4]byte
	Fvsa_dfaclentp uintptr
	Fvsa_aclentsz  uint64
	Fvsa_aclflags  uint32
	F__ccgo_pad2   [4]byte
}

type Vsecattr_t = Vsecattr

type Caller_context = struct {
	Fcc_pid       int32
	Fcc_sysid     int32
	Fcc_caller_id uint64
	Fcc_flags     uint64
}

type Caller_context_t = Caller_context
type Fid = struct {
	Fun struct {
		Ffid_pad     int64
		F__ccgo_pad1 [64]byte
	}
}

type Statvfs = struct {
	Ff_bsize    uint64
	Ff_frsize   uint64
	Ff_blocks   uint64
	Ff_bfree    uint64
	Ff_bavail   uint64
	Ff_files    uint64
	Ff_ffree    uint64
	Ff_favail   uint64
	Ff_fsid     uint64
	Ff_basetype [16]int8
	Ff_flag     uint64
	Ff_namemax  uint64
	Ff_fstr     [32]int8
}

type Statvfs_t = Statvfs

type Statvfs64 = struct {
	Ff_bsize    uint64
	Ff_frsize   uint64
	Ff_blocks   uint64
	Ff_bfree    uint64
	Ff_bavail   uint64
	Ff_files    uint64
	Ff_ffree    uint64
	Ff_favail   uint64
	Ff_fsid     uint64
	Ff_basetype [16]int8
	Ff_flag     uint64
	Ff_namemax  uint64
	Ff_fstr     [32]int8
}

type Statvfs64_t = Statvfs64

type Avl_node = struct {
	Favl_child [2]uintptr
	Favl_pcb   uint64
}

type Avl_tree = struct {
	Favl_root     uintptr
	Favl_compar   uintptr
	Favl_offset   uint64
	Favl_numnodes uint64
	Favl_size     uint64
}

type Avl_tree_t = Avl_tree

type Avl_node_t = Avl_node

type Avl_index_t = uint64

type Vfsops = struct {
	Fvfs_mount     uintptr
	Fvfs_unmount   uintptr
	Fvfs_root      uintptr
	Fvfs_statvfs   uintptr
	Fvfs_sync      uintptr
	Fvfs_vget      uintptr
	Fvfs_mountroot uintptr
	Fvfs_freevfs   uintptr
	Fvfs_vnstate   uintptr
}

type Vfsops_t = Vfsops

type Fsid_t = struct{ Fval [2]int32 }

type Fid_t = Fid

type Fid32_t = Fid_t

type Mntopt = struct {
	Fmo_name     uintptr
	Fmo_cancel   uintptr
	Fmo_arg      uintptr
	Fmo_flags    int32
	F__ccgo_pad1 [4]byte
	Fmo_data     uintptr
}

type Mntopt_t = Mntopt

type Mntopts = struct {
	Fmo_count    uint32
	F__ccgo_pad1 [4]byte
	Fmo_list     uintptr
}

type Mntopts_t = Mntopts

type Vskstat_anchor = struct {
	Fvsk_node Avl_node_t
	Fvsk_ksp  uintptr
	Fvsk_fsid uint64
}

type Vsk_anchor_t = Vskstat_anchor

type Vfs_t = Vfs

type Vfs_feature_t = uint64

type Mounta = struct {
	Fspec        uintptr
	Fdir         uintptr
	Fflags       int32
	F__ccgo_pad1 [4]byte
	Ffstype      uintptr
	Fdataptr     uintptr
	Fdatalen     int32
	F__ccgo_pad2 [4]byte
	Foptptr      uintptr
	Foptlen      int32
	F__ccgo_pad3 [4]byte
}

type Whymountroot_t = uint32
type Vntrans_t = uint32

type Vfssw = struct {
	Fvsw_name     uintptr
	Fvsw_init     uintptr
	Fvsw_flag     int32
	F__ccgo_pad1  [4]byte
	Fvsw_optproto Mntopts_t
	Fvsw_count    uint32
	F__ccgo_pad2  [4]byte
	Fvsw_lock     Kmutex_t
	Fvsw_vfsops   Vfsops_t
}

type Vfssw_t = Vfssw

type Vfsdef_v51 = struct {
	Fdef_version int32
	F__ccgo_pad1 [4]byte
	Fname        uintptr
	Finit        uintptr
	Fflags       int32
	F__ccgo_pad2 [4]byte
	Foptproto    uintptr
}

type Vfsdef_v5 = Vfsdef_v51

type Vfsdef_t = Vfsdef_v51

var _ int8
