// Code generated by 'ccgo dirent/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -o dirent/dirent_linux_arm.go -pkgname dirent', DO NOT EDIT.

package dirent

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	AIO_PRIO_DELTA_MAX                   = 20
	DELAYTIMER_MAX                       = 2147483647
	HOST_NAME_MAX                        = 64
	LOGIN_NAME_MAX                       = 256
	MAXNAMLEN                            = 255
	MAX_CANON                            = 255
	MAX_INPUT                            = 255
	MQ_PRIO_MAX                          = 32768
	NAME_MAX                             = 255
	NGROUPS_MAX                          = 65536
	PATH_MAX                             = 4096
	PIPE_BUF                             = 4096
	PTHREAD_DESTRUCTOR_ITERATIONS        = 4
	PTHREAD_KEYS_MAX                     = 1024
	PTHREAD_STACK_MIN                    = 16384
	RTSIG_MAX                            = 32
	SEM_VALUE_MAX                        = 2147483647
	TTY_NAME_MAX                         = 32
	XATTR_LIST_MAX                       = 65536
	XATTR_NAME_MAX                       = 255
	XATTR_SIZE_MAX                       = 65536
	X_ATFILE_SOURCE                      = 1
	X_BITS_POSIX1_LIM_H                  = 1
	X_BITS_TIME64_H                      = 1
	X_BITS_TYPESIZES_H                   = 1
	X_BITS_TYPES_H                       = 1
	X_BSD_SIZE_T_                        = 0
	X_BSD_SIZE_T_DEFINED_                = 0
	X_DEFAULT_SOURCE                     = 1
	X_DIRENT_H                           = 1
	X_DIRENT_HAVE_D_OFF                  = 0
	X_DIRENT_HAVE_D_RECLEN               = 0
	X_DIRENT_HAVE_D_TYPE                 = 0
	X_DIRENT_MATCHES_DIRENT64            = 0
	X_FEATURES_H                         = 1
	X_FILE_OFFSET_BITS                   = 64
	X_GCC_SIZE_T                         = 0
	X_LINUX_LIMITS_H                     = 0
	X_POSIX_AIO_LISTIO_MAX               = 2
	X_POSIX_AIO_MAX                      = 1
	X_POSIX_ARG_MAX                      = 4096
	X_POSIX_CHILD_MAX                    = 25
	X_POSIX_CLOCKRES_MIN                 = 20000000
	X_POSIX_C_SOURCE                     = 200809
	X_POSIX_DELAYTIMER_MAX               = 32
	X_POSIX_HOST_NAME_MAX                = 255
	X_POSIX_LINK_MAX                     = 8
	X_POSIX_LOGIN_NAME_MAX               = 9
	X_POSIX_MAX_CANON                    = 255
	X_POSIX_MAX_INPUT                    = 255
	X_POSIX_MQ_OPEN_MAX                  = 8
	X_POSIX_MQ_PRIO_MAX                  = 32
	X_POSIX_NAME_MAX                     = 14
	X_POSIX_NGROUPS_MAX                  = 8
	X_POSIX_OPEN_MAX                     = 20
	X_POSIX_PATH_MAX                     = 256
	X_POSIX_PIPE_BUF                     = 512
	X_POSIX_RE_DUP_MAX                   = 255
	X_POSIX_RTSIG_MAX                    = 8
	X_POSIX_SEM_NSEMS_MAX                = 256
	X_POSIX_SEM_VALUE_MAX                = 32767
	X_POSIX_SIGQUEUE_MAX                 = 32
	X_POSIX_SOURCE                       = 1
	X_POSIX_SSIZE_MAX                    = 32767
	X_POSIX_STREAM_MAX                   = 8
	X_POSIX_SYMLINK_MAX                  = 255
	X_POSIX_SYMLOOP_MAX                  = 8
	X_POSIX_THREAD_DESTRUCTOR_ITERATIONS = 4
	X_POSIX_THREAD_KEYS_MAX              = 128
	X_POSIX_THREAD_THREADS_MAX           = 64
	X_POSIX_TIMER_MAX                    = 32
	X_POSIX_TTY_NAME_MAX                 = 9
	X_POSIX_TZNAME_MAX                   = 6
	X_SIZET_                             = 0
	X_SIZE_T                             = 0
	X_SIZE_T_                            = 0
	X_SIZE_T_DECLARED                    = 0
	X_SIZE_T_DEFINED                     = 0
	X_SIZE_T_DEFINED_                    = 0
	X_STDC_PREDEF_H                      = 1
	X_SYS_CDEFS_H                        = 1
	X_SYS_SIZE_T_H                       = 0
	X_T_SIZE                             = 0
	X_T_SIZE_                            = 0
	Linux                                = 1
	Unix                                 = 1
)

const (
	DT_UNKNOWN = 0
	DT_FIFO    = 1
	DT_CHR     = 2
	DT_DIR     = 4
	DT_BLK     = 6
	DT_REG     = 8
	DT_LNK     = 10
	DT_SOCK    = 12
	DT_WHT     = 14
)

type Ptrdiff_t = int32

type Size_t = uint32

type Wchar_t = uint32

type X__builtin_va_list = uintptr
type X__float128 = float64

type X__u_char = uint8
type X__u_short = uint16
type X__u_int = uint32
type X__u_long = uint32

type X__int8_t = int8
type X__uint8_t = uint8
type X__int16_t = int16
type X__uint16_t = uint16
type X__int32_t = int32
type X__uint32_t = uint32
type X__int64_t = int64
type X__uint64_t = uint64

type X__int_least8_t = X__int8_t
type X__uint_least8_t = X__uint8_t
type X__int_least16_t = X__int16_t
type X__uint_least16_t = X__uint16_t
type X__int_least32_t = X__int32_t
type X__uint_least32_t = X__uint32_t
type X__int_least64_t = X__int64_t
type X__uint_least64_t = X__uint64_t

type X__quad_t = int64
type X__u_quad_t = uint64

type X__intmax_t = int64
type X__uintmax_t = uint64

type X__dev_t = X__uint64_t
type X__uid_t = uint32
type X__gid_t = uint32
type X__ino_t = uint32
type X__ino64_t = X__uint64_t
type X__mode_t = uint32
type X__nlink_t = uint32
type X__off_t = int32
type X__off64_t = X__int64_t
type X__pid_t = int32
type X__fsid_t = struct{ F__val [2]int32 }
type X__clock_t = int32
type X__rlim_t = uint32
type X__rlim64_t = X__uint64_t
type X__id_t = uint32
type X__time_t = int32
type X__useconds_t = uint32
type X__suseconds_t = int32

type X__daddr_t = int32
type X__key_t = int32

type X__clockid_t = int32

type X__timer_t = uintptr

type X__blksize_t = int32

type X__blkcnt_t = int32
type X__blkcnt64_t = X__int64_t

type X__fsblkcnt_t = uint32
type X__fsblkcnt64_t = X__uint64_t

type X__fsfilcnt_t = uint32
type X__fsfilcnt64_t = X__uint64_t

type X__fsword_t = int32

type X__ssize_t = int32

type X__syscall_slong_t = int32

type X__syscall_ulong_t = uint32

type X__loff_t = X__off64_t
type X__caddr_t = uintptr

type X__intptr_t = int32

type X__socklen_t = uint32

type X__sig_atomic_t = int32

type X__time64_t = X__int64_t

type Dirent = struct {
	Fd_ino       X__ino64_t
	Fd_off       X__off64_t
	Fd_reclen    uint16
	Fd_type      uint8
	Fd_name      [256]uint8
	F__ccgo_pad1 [5]byte
}

var _ uint8
