// Code generated by 'ccgo dirent/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o dirent/dirent_darwin_arm64.go -pkgname dirent', DO NOT EDIT.

package dirent

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	DIRBLKSIZ                              = 1024
	DTF_HIDEW                              = 0x0001
	DTF_NODUP                              = 0x0002
	DTF_REWIND                             = 0x0004
	DT_BLK                                 = 6
	DT_CHR                                 = 2
	DT_DIR                                 = 4
	DT_FIFO                                = 1
	DT_LNK                                 = 10
	DT_REG                                 = 8
	DT_SOCK                                = 12
	DT_UNKNOWN                             = 0
	DT_WHT                                 = 14
	MAC_OS_VERSION_11_0                    = 110000
	MAC_OS_VERSION_12_0                    = 120000
	MAC_OS_X_VERSION_10_0                  = 1000
	MAC_OS_X_VERSION_10_1                  = 1010
	MAC_OS_X_VERSION_10_10                 = 101000
	MAC_OS_X_VERSION_10_10_2               = 101002
	MAC_OS_X_VERSION_10_10_3               = 101003
	MAC_OS_X_VERSION_10_11                 = 101100
	MAC_OS_X_VERSION_10_11_2               = 101102
	MAC_OS_X_VERSION_10_11_3               = 101103
	MAC_OS_X_VERSION_10_11_4               = 101104
	MAC_OS_X_VERSION_10_12                 = 101200
	MAC_OS_X_VERSION_10_12_1               = 101201
	MAC_OS_X_VERSION_10_12_2               = 101202
	MAC_OS_X_VERSION_10_12_4               = 101204
	MAC_OS_X_VERSION_10_13                 = 101300
	MAC_OS_X_VERSION_10_13_1               = 101301
	MAC_OS_X_VERSION_10_13_2               = 101302
	MAC_OS_X_VERSION_10_13_4               = 101304
	MAC_OS_X_VERSION_10_14                 = 101400
	MAC_OS_X_VERSION_10_14_1               = 101401
	MAC_OS_X_VERSION_10_14_4               = 101404
	MAC_OS_X_VERSION_10_14_6               = 101406
	MAC_OS_X_VERSION_10_15                 = 101500
	MAC_OS_X_VERSION_10_15_1               = 101501
	MAC_OS_X_VERSION_10_16                 = 101600
	MAC_OS_X_VERSION_10_2                  = 1020
	MAC_OS_X_VERSION_10_3                  = 1030
	MAC_OS_X_VERSION_10_4                  = 1040
	MAC_OS_X_VERSION_10_5                  = 1050
	MAC_OS_X_VERSION_10_6                  = 1060
	MAC_OS_X_VERSION_10_7                  = 1070
	MAC_OS_X_VERSION_10_8                  = 1080
	MAC_OS_X_VERSION_10_9                  = 1090
	MAXNAMLEN                              = 255
	X_BSD_ARM__TYPES_H_                    = 0
	X_BSD_MACHINE__TYPES_H_                = 0
	X_CDEFS_H_                             = 0
	X_DARWIN_FEATURE_64_BIT_INODE          = 1
	X_DARWIN_FEATURE_ONLY_64_BIT_INODE     = 1
	X_DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1
	X_DARWIN_FEATURE_ONLY_VERS_1050        = 1
	X_DARWIN_FEATURE_UNIX_CONFORMANCE      = 3
	X_DIRENT_H_                            = 0
	X_FILE_OFFSET_BITS                     = 64
	X_FORTIFY_SOURCE                       = 2
	X_INO_T                                = 0
	X_LP64                                 = 1
	X_Nonnull                              = 0
	X_Null_unspecified                     = 0
	X_Nullable                             = 0
	X_SYS_DIRENT_H                         = 0
	X_SYS__PTHREAD_TYPES_H_                = 0
	X_SYS__TYPES_H_                        = 0
)

type Ptrdiff_t = int64

type Size_t = uint64

type Wchar_t = int32

type X__int128_t = struct {
	Flo int64
	Fhi int64
}
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
}

type X__builtin_va_list = uintptr
type X__float128 = float64

var X__darwin_check_fd_set_overflow uintptr

type X__int8_t = int8
type X__uint8_t = uint8
type X__int16_t = int16
type X__uint16_t = uint16
type X__int32_t = int32
type X__uint32_t = uint32
type X__int64_t = int64
type X__uint64_t = uint64

type X__darwin_intptr_t = int64
type X__darwin_natural_t = uint32

type X__darwin_ct_rune_t = int32

type X__mbstate_t = struct {
	F__ccgo_pad1 [0]uint64
	F__mbstate8  [128]int8
}

type X__darwin_mbstate_t = X__mbstate_t

type X__darwin_ptrdiff_t = int64

type X__darwin_size_t = uint64

type X__darwin_va_list = X__builtin_va_list

type X__darwin_wchar_t = int32

type X__darwin_rune_t = X__darwin_wchar_t

type X__darwin_wint_t = int32

type X__darwin_clock_t = uint64
type X__darwin_socklen_t = X__uint32_t
type X__darwin_ssize_t = int64
type X__darwin_time_t = int64

type X__darwin_blkcnt_t = X__int64_t
type X__darwin_blksize_t = X__int32_t
type X__darwin_dev_t = X__int32_t
type X__darwin_fsblkcnt_t = uint32
type X__darwin_fsfilcnt_t = uint32
type X__darwin_gid_t = X__uint32_t
type X__darwin_id_t = X__uint32_t
type X__darwin_ino64_t = X__uint64_t
type X__darwin_ino_t = X__darwin_ino64_t
type X__darwin_mach_port_name_t = X__darwin_natural_t
type X__darwin_mach_port_t = X__darwin_mach_port_name_t
type X__darwin_mode_t = X__uint16_t
type X__darwin_off_t = X__int64_t
type X__darwin_pid_t = X__int32_t
type X__darwin_sigset_t = X__uint32_t
type X__darwin_suseconds_t = X__int32_t
type X__darwin_uid_t = X__uint32_t
type X__darwin_useconds_t = X__uint32_t
type X__darwin_uuid_t = [16]uint8
type X__darwin_uuid_string_t = [37]int8

type X__darwin_pthread_handler_rec = struct {
	F__routine uintptr
	F__arg     uintptr
	F__next    uintptr
}

type X_opaque_pthread_attr_t = struct {
	F__sig    int64
	F__opaque [56]int8
}

type X_opaque_pthread_cond_t = struct {
	F__sig    int64
	F__opaque [40]int8
}

type X_opaque_pthread_condattr_t = struct {
	F__sig    int64
	F__opaque [8]int8
}

type X_opaque_pthread_mutex_t = struct {
	F__sig    int64
	F__opaque [56]int8
}

type X_opaque_pthread_mutexattr_t = struct {
	F__sig    int64
	F__opaque [8]int8
}

type X_opaque_pthread_once_t = struct {
	F__sig    int64
	F__opaque [8]int8
}

type X_opaque_pthread_rwlock_t = struct {
	F__sig    int64
	F__opaque [192]int8
}

type X_opaque_pthread_rwlockattr_t = struct {
	F__sig    int64
	F__opaque [16]int8
}

type X_opaque_pthread_t = struct {
	F__sig           int64
	F__cleanup_stack uintptr
	F__opaque        [8176]int8
}

type X__darwin_pthread_attr_t = X_opaque_pthread_attr_t
type X__darwin_pthread_cond_t = X_opaque_pthread_cond_t
type X__darwin_pthread_condattr_t = X_opaque_pthread_condattr_t
type X__darwin_pthread_key_t = uint64
type X__darwin_pthread_mutex_t = X_opaque_pthread_mutex_t
type X__darwin_pthread_mutexattr_t = X_opaque_pthread_mutexattr_t
type X__darwin_pthread_once_t = X_opaque_pthread_once_t
type X__darwin_pthread_rwlock_t = X_opaque_pthread_rwlock_t
type X__darwin_pthread_rwlockattr_t = X_opaque_pthread_rwlockattr_t
type X__darwin_pthread_t = uintptr

type X__darwin_nl_item = int32
type X__darwin_wctrans_t = int32
type X__darwin_wctype_t = X__uint32_t

type Ino_t = X__darwin_ino_t

type Dirent = struct {
	Fd_ino       X__uint64_t
	Fd_seekoff   X__uint64_t
	Fd_reclen    X__uint16_t
	Fd_namlen    X__uint16_t
	Fd_type      X__uint8_t
	Fd_name      [1024]int8
	F__ccgo_pad1 [3]byte
}

type DIR = struct {
	F__dd_fd     int32
	F__ccgo_pad1 [4]byte
	F__dd_loc    int64
	F__dd_size   int64
	F__dd_buf    uintptr
	F__dd_len    int32
	F__ccgo_pad2 [4]byte
	F__dd_seek   int64
	F__padding   int64
	F__dd_flags  int32
	F__ccgo_pad3 [4]byte
	F__dd_lock   X__darwin_pthread_mutex_t
	F__dd_td     uintptr
}

var _ int8
