// Code generated by 'ccgo locale/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o locale/locale_netbsd_arm.go -pkgname locale', DO NOT EDIT.

package locale

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	LC_ALL              = 0
	LC_COLLATE          = 1
	LC_CTYPE            = 2
	LC_MESSAGES         = 6
	LC_MONETARY         = 3
	LC_NUMERIC          = 4
	LC_TIME             = 5
	X_ARM_ARCH_4T       = 0
	X_ARM_ARCH_5        = 0
	X_ARM_ARCH_5T       = 0
	X_ARM_ARCH_6        = 0
	X_ARM_ARCH_7        = 0
	X_ARM_ARCH_DWORD_OK = 0
	X_ARM_ARCH_T2       = 0
	X_ARM_CDEFS_H_      = 0
	X_FILE_OFFSET_BITS  = 64
	X_LC_LAST           = 7
	X_LOCALE_H_         = 0
	X_NETBSD_SOURCE     = 1
	X_SYS_CDEFS_ELF_H_  = 0
	X_SYS_CDEFS_H_      = 0
	X_SYS_NULL_H_       = 0
)

type Ptrdiff_t = int32

type Size_t = uint32

type Wchar_t = int32

type X__builtin_va_list = uintptr
type X__float128 = float64

type Lconv = struct {
	Fdecimal_point      uintptr
	Fthousands_sep      uintptr
	Fgrouping           uintptr
	Fint_curr_symbol    uintptr
	Fcurrency_symbol    uintptr
	Fmon_decimal_point  uintptr
	Fmon_thousands_sep  uintptr
	Fmon_grouping       uintptr
	Fpositive_sign      uintptr
	Fnegative_sign      uintptr
	Fint_frac_digits    uint8
	Ffrac_digits        uint8
	Fp_cs_precedes      uint8
	Fp_sep_by_space     uint8
	Fn_cs_precedes      uint8
	Fn_sep_by_space     uint8
	Fp_sign_posn        uint8
	Fn_sign_posn        uint8
	Fint_p_cs_precedes  uint8
	Fint_n_cs_precedes  uint8
	Fint_p_sep_by_space uint8
	Fint_n_sep_by_space uint8
	Fint_p_sign_posn    uint8
	Fint_n_sign_posn    uint8
	F__ccgo_pad1        [2]byte
}

type Locale_t = uintptr

var _ uint8
