// Code generated by 'ccgo locale/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o locale/locale_freebsd_arm.go -pkgname locale', DO NOT EDIT.

package locale

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	LC_ALL             = 0
	LC_ALL_MASK        = 63
	LC_COLLATE         = 1
	LC_COLLATE_MASK    = 1
	LC_CTYPE           = 2
	LC_CTYPE_MASK      = 2
	LC_MESSAGES        = 6
	LC_MESSAGES_MASK   = 32
	LC_MONETARY        = 3
	LC_MONETARY_MASK   = 4
	LC_NUMERIC         = 4
	LC_NUMERIC_MASK    = 8
	LC_TIME            = 5
	LC_TIME_MASK       = 16
	LC_VERSION_MASK    = 64
	X_FILE_OFFSET_BITS = 64
	X_ILP32            = 1
	X_LC_LAST          = 7
	X_LOCALE_H_        = 0
	X_LOCALE_T_DEFINED = 0
	X_Nonnull          = 0
	X_Null_unspecified = 0
	X_Nullable         = 0
	X_SYS_CDEFS_H_     = 0
	X_XLOCALE_LOCALE_H = 0
	Unix               = 1
)

type Ptrdiff_t = int32

type Size_t = uint32

type Wchar_t = uint32

type X__builtin_va_list = uintptr
type X__float128 = float64

type Lconv = struct {
	Fdecimal_point      uintptr
	Fthousands_sep      uintptr
	Fgrouping           uintptr
	Fint_curr_symbol    uintptr
	Fcurrency_symbol    uintptr
	Fmon_decimal_point  uintptr
	Fmon_thousands_sep  uintptr
	Fmon_grouping       uintptr
	Fpositive_sign      uintptr
	Fnegative_sign      uintptr
	Fint_frac_digits    uint8
	Ffrac_digits        uint8
	Fp_cs_precedes      uint8
	Fp_sep_by_space     uint8
	Fn_cs_precedes      uint8
	Fn_sep_by_space     uint8
	Fp_sign_posn        uint8
	Fn_sign_posn        uint8
	Fint_p_cs_precedes  uint8
	Fint_n_cs_precedes  uint8
	Fint_p_sep_by_space uint8
	Fint_n_sep_by_space uint8
	Fint_p_sign_posn    uint8
	Fint_n_sign_posn    uint8
	F__ccgo_pad1        [2]byte
}

type Locale_t = uintptr

var _ uint8
