// Code generated by 'ccgo locale/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o locale/locale_illumos_amd64.go -pkgname locale', DO NOT EDIT.

package locale

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	LC_ALL                          = 6
	LC_ALL_MASK                     = 63
	LC_COLLATE                      = 3
	LC_COLLATE_MASK                 = 8
	LC_CTYPE                        = 0
	LC_CTYPE_MASK                   = 1
	LC_MESSAGES                     = 5
	LC_MESSAGES_MASK                = 32
	LC_MONETARY                     = 4
	LC_MONETARY_MASK                = 16
	LC_NUMERIC                      = 1
	LC_NUMERIC_MASK                 = 2
	LC_TIME                         = 2
	LC_TIME_MASK                    = 4
	TEXTDOMAINMAX                   = 256
	X_ALIGNMENT_REQUIRED            = 1
	X_BIT_FIELDS_LTOH               = 0
	X_BOOL_ALIGNMENT                = 1
	X_CHAR_ALIGNMENT                = 1
	X_CHAR_IS_SIGNED                = 0
	X_DMA_USES_PHYSADDR             = 0
	X_DONT_USE_1275_GENERIC_NAMES   = 0
	X_DOUBLE_ALIGNMENT              = 8
	X_DOUBLE_COMPLEX_ALIGNMENT      = 8
	X_DTRACE_VERSION                = 1
	X_FILE_OFFSET_BITS              = 64
	X_FIRMWARE_NEEDS_FDISK          = 0
	X_FLOAT_ALIGNMENT               = 4
	X_FLOAT_COMPLEX_ALIGNMENT       = 4
	X_HAVE_CPUID_INSN               = 0
	X_IEEE_754                      = 0
	X_INT_ALIGNMENT                 = 4
	X_ISO_CPP_14882_1998            = 0
	X_ISO_C_9899_1999               = 0
	X_ISO_C_9899_2011               = 0
	X_ISO_LOCALE_ISO_H              = 0
	X_LARGEFILE64_SOURCE            = 1
	X_LARGEFILE_SOURCE              = 1
	X_LIBINTL_H                     = 0
	X_LITTLE_ENDIAN                 = 0
	X_LOCALE_H                      = 0
	X_LOCALE_T                      = 0
	X_LONGLONG_TYPE                 = 0
	X_LONG_ALIGNMENT                = 8
	X_LONG_DOUBLE_ALIGNMENT         = 16
	X_LONG_DOUBLE_COMPLEX_ALIGNMENT = 16
	X_LONG_LONG_ALIGNMENT           = 8
	X_LONG_LONG_ALIGNMENT_32        = 4
	X_LONG_LONG_LTOH                = 0
	X_LP64                          = 1
	X_LastCategory                  = 5
	X_MAX_ALIGNMENT                 = 16
	X_MULTI_DATAMODEL               = 0
	X_NORETURN_KYWD                 = 0
	X_POINTER_ALIGNMENT             = 8
	X_PSM_MODULES                   = 0
	X_RESTRICT_KYWD                 = 0
	X_RTC_CONFIG                    = 0
	X_SHORT_ALIGNMENT               = 2
	X_SOFT_HOSTID                   = 0
	X_STACK_GROWS_DOWNWARD          = 0
	X_STDC_C11                      = 0
	X_STDC_C99                      = 0
	X_SUNOS_VTOC_16                 = 0
	X_SYS_CCOMPILE_H                = 0
	X_SYS_FEATURE_TESTS_H           = 0
	X_SYS_ISA_DEFS_H                = 0
	X_SYS_NULL_H                    = 0
	X_WCHAR_T                       = 0
	X_XOPEN_VERSION                 = 3
	Sun                             = 1
	Unix                            = 1
)

type Ptrdiff_t = int64

type Size_t = uint64

type Wchar_t = int32

type X__int128_t = struct {
	Flo int64
	Fhi int64
}
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
}

type X__builtin_va_list = uintptr
type X__float128 = float64

type Lconv = struct {
	Fdecimal_point     uintptr
	Fthousands_sep     uintptr
	Fgrouping          uintptr
	Fint_curr_symbol   uintptr
	Fcurrency_symbol   uintptr
	Fmon_decimal_point uintptr
	Fmon_thousands_sep uintptr
	Fmon_grouping      uintptr
	Fpositive_sign     uintptr
	Fnegative_sign     uintptr
	Fint_frac_digits   int8
	Ffrac_digits       int8
	Fp_cs_precedes     int8
	Fp_sep_by_space    int8
	Fn_cs_precedes     int8
	Fn_sep_by_space    int8
	Fp_sign_posn       int8
	Fn_sign_posn       int8
}

type Locale_t = uintptr

var _ int8
