// Code generated by 'ccgo locale/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o locale/locale_linux_ppc64le.go -pkgname locale', DO NOT EDIT.

package locale

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	LC_ADDRESS                = 9
	LC_ADDRESS_MASK           = 512
	LC_ALL                    = 6
	LC_ALL_MASK               = 8127
	LC_COLLATE                = 3
	LC_COLLATE_MASK           = 8
	LC_CTYPE                  = 0
	LC_CTYPE_MASK             = 1
	LC_IDENTIFICATION         = 12
	LC_IDENTIFICATION_MASK    = 4096
	LC_MEASUREMENT            = 11
	LC_MEASUREMENT_MASK       = 2048
	LC_MESSAGES               = 5
	LC_MESSAGES_MASK          = 32
	LC_MONETARY               = 4
	LC_MONETARY_MASK          = 16
	LC_NAME                   = 8
	LC_NAME_MASK              = 256
	LC_NUMERIC                = 1
	LC_NUMERIC_MASK           = 2
	LC_PAPER                  = 7
	LC_PAPER_MASK             = 128
	LC_TELEPHONE              = 10
	LC_TELEPHONE_MASK         = 1024
	LC_TIME                   = 2
	LC_TIME_MASK              = 4
	X_ARCH_PPC                = 1
	X_ARCH_PPC64              = 1
	X_ARCH_PPCGR              = 1
	X_ARCH_PPCSQ              = 1
	X_ARCH_PWR4               = 1
	X_ARCH_PWR5               = 1
	X_ARCH_PWR5X              = 1
	X_ARCH_PWR6               = 1
	X_ARCH_PWR7               = 1
	X_ARCH_PWR8               = 1
	X_ATFILE_SOURCE           = 1
	X_BITS_LOCALE_H           = 1
	X_BITS_TYPES_LOCALE_T_H   = 1
	X_BITS_TYPES___LOCALE_T_H = 1
	X_CALL_ELF                = 2
	X_CALL_LINUX              = 1
	X_DEFAULT_SOURCE          = 1
	X_FEATURES_H              = 1
	X_FILE_OFFSET_BITS        = 64
	X_LITTLE_ENDIAN           = 1
	X_LOCALE_H                = 1
	X_LP64                    = 1
	X_POSIX_C_SOURCE          = 200809
	X_POSIX_SOURCE            = 1
	X_STDC_PREDEF_H           = 1
	X_SYS_CDEFS_H             = 1
	Linux                     = 1
	Unix                      = 1
)

type Ptrdiff_t = int64

type Size_t = uint64

type Wchar_t = int32

type X__int128_t = struct {
	Flo int64
	Fhi int64
}
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
}

type X__builtin_va_list = uintptr
type X__ieee128 = float64

type Lconv = struct {
	Fdecimal_point      uintptr
	Fthousands_sep      uintptr
	Fgrouping           uintptr
	Fint_curr_symbol    uintptr
	Fcurrency_symbol    uintptr
	Fmon_decimal_point  uintptr
	Fmon_thousands_sep  uintptr
	Fmon_grouping       uintptr
	Fpositive_sign      uintptr
	Fnegative_sign      uintptr
	Fint_frac_digits    uint8
	Ffrac_digits        uint8
	Fp_cs_precedes      uint8
	Fp_sep_by_space     uint8
	Fn_cs_precedes      uint8
	Fn_sep_by_space     uint8
	Fp_sign_posn        uint8
	Fn_sign_posn        uint8
	Fint_p_cs_precedes  uint8
	Fint_p_sep_by_space uint8
	Fint_n_cs_precedes  uint8
	Fint_n_sep_by_space uint8
	Fint_p_sign_posn    uint8
	Fint_n_sign_posn    uint8
	F__ccgo_pad1        [2]byte
}

type X__locale_struct = struct {
	F__locales       [13]uintptr
	F__ctype_b       uintptr
	F__ctype_tolower uintptr
	F__ctype_toupper uintptr
	F__names         [13]uintptr
}

type X__locale_t = uintptr

type Locale_t = X__locale_t

var _ uint8
